### PR TITLE
fix unneeded use of pwd in REPL prompt function

### LINKED ISSUE #547: Unable to open Pkg REPL mode
```
julia> ┌ Error: Error in the keymap
│   exception =
│    getcwd: no such file or directory (ENOENT)
│    Stacktrace:
│     [1] uv_error at ./libuv.jl:80 [inlined]
│     [2] uv_error at ./libuv.jl:79 [inlined]
│     [3] pwd() at ./file.jl:53
│     [4] promptf() at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:989
│     [5] #invokelatest#1 at ./essentials.jl:660 [inlined]
│     [6] invokelatest at ./essentials.jl:659 [inlined]
│     [7] prompt_string at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:357 [inlined]
│     [8] write_prompt(::REPL.Terminals.TerminalBuffer, ::typeof(Pkg.REPLMode.promptf)) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1193
│     [9] write_prompt(::REPL.Terminals.TerminalBuffer, ::REPL.LineEdit.Prompt) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1185
│     [10] write_prompt at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1178 [inlined]
│     [11] #refresh_multi_line#16(::Int64, ::Bool, ::Function, ::REPL.Terminals.TerminalBuffer, ::REPL.Terminals.TTYTerminal, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::REPL.LineEdit.InputAreaState, ::REPL.LineEdit.PromptState) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:376
│     [12] #refresh_multi_line at ./none:0 [inlined]
│     [13] #refresh_multi_line#37 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1602 [inlined]
│     [14] refresh_multi_line(::REPL.Terminals.TerminalBuffer, ::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.PromptState) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1601
│     [15] #refresh_multi_line#14(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::REPL.Terminals.TerminalBuffer, ::REPL.LineEdit.PromptState) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:360
│     [16] refresh_multi_line at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:360 [inlined]
│     [17] refresh_line at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1173 [inlined]
│     [18] activate(::REPL.LineEdit.Prompt, ::REPL.LineEdit.PromptState, ::REPL.Terminals.TerminalBuffer, ::REPL.Terminals.TTYTerminal) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:2127
│     [19] transition(::getfield(Pkg.REPLMode, Symbol("##36#38")){REPL.LineEdit.MIState,REPL.LineEdit.Prompt}, ::REPL.LineEdit.MIState, ::REPL.LineEdit.Prompt) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:2157
│     [20] (::getfield(Pkg.REPLMode, Symbol("##35#37")){REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::REPL.LineEditREPL, ::Vararg{Any,N} where N) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:1069
│     [21] #invokelatest#1 at ./essentials.jl:660 [inlined]
│     [22] invokelatest at ./essentials.jl:659 [inlined]
│     [23] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(Pkg.REPLMode, Symbol("##35#37")){REPL.LineEdit.Prompt},String})(::REPL.LineEdit.MIState, ::REPL.LineEditREPL) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:1302
│     [24] prompt!(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:2311
│     [25] run_interface(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:2212
│     [26] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:1026
│     [27] run_repl(::REPL.LineEditREPL, ::getfield(Base, Symbol("##824#826"))) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:187
│     [28] (::getfield(Base, Symbol("##823#825")){Bool,Bool,Bool,Bool})(::Module) at ./logging.jl:299
│     [29] #invokelatest#1 at ./essentials.jl:660 [inlined]
│     [30] invokelatest at ./essentials.jl:659 [inlined]
│     [31] macro expansion at ./logging.jl:296 [inlined]
│     [32] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:335
│     [33] exec_options(::Base.JLOptions) at ./client.jl:247
│     [34] _start() at ./client.jl:427
└ @ REPL.LineEdit /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/LineEdit.jl:2313
```
```
julia> versioninfo()
Julia Version 0.7.0-beta2.0
Commit b145832402* (2018-07-13 19:54 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
```

### PR DESCRIPTION
**Pull request by KristofferC**
Likely left when pwd had some importance to the project being used.

Fixes #547

### CODE REVIEW

File: test/repl.jl [hunk 1]
```diff
@@ -550,11 +550,11 @@ end
 
         newname = "NewName"
         set_name(projfile_path, newname)
-        @test Pkg.REPLMode.promptf() == "($env_name) pkg> "
+        @test Pkg.REPLMode.promptf() == "($newname) pkg> "
```
Comment (KristofferC) [inline test/repl.jl]: @00vareladavid can you explain these tests. Why should it not be `newname` here? We changed the name in the current project file? What am I missing.

Comment (00vareladavid) [reply test/repl.jl]: Yes, I wrote these tests just after `activate` was introduced. Right before, we were still using `pwd` to determine the active project. I did comment on it (because I thought it was weird) [here](https://github.com/JuliaLang/Pkg.jl/pull/466#issuecomment-402837253). In hindsight, I should have made a bigger fuss about it.
