### PR TITLE
Safer Project.toml and Manifest.toml printing

### LINKED ISSUE #1202: KeyError in Types.jl wipes out Manifest.toml
Working in an environment where I have "re-named" a package (named `Foo` -> `Bar`, but kept the same UUID, so that I can submit a paper with supplementary code without identifying the authors), when I added a new package to the repository that depended on the re-named package, I got the following error:

```
ERROR: KeyError: key "Zygote" not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] #109 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1504 [inlined]
 [3] _all(::getfield(Pkg.Types, Symbol("##109#111")){Dict{String,Bool}}, ::Dict{String,Base.UUID}, ::Colon) at ./reduce.jl:663
 [4] all at ./reduce.jl:658 [inlined]
 [5] destructure(::Dict{Base.UUID,Pkg.Types.PackageEntry}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types$
jl:1504
 [6] write_manifest at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1545 [inlined]
 [7] #117 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1542 [inlined]
 [8] #open#310(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:truncate,),Tuple{Bool}}}, ::Function, ::getfield(Pkg.Types, Symbol("$
#117#118")){Dict{Base.UUID,Pkg.Types.PackageEntry}}, ::String) at ./iostream.jl:369
 [9] #open at ./none:0 [inlined]
 [10] write_manifest at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1541 [inlined]
 [11] #write_manifest#119(::Bool, ::Function, ::Dict{Base.UUID,Pkg.Types.PackageEntry}, ::Pkg.Types.EnvCache, ::Pkg.Types.EnvCache, ::Pkg.Types.C$
ntext) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1557
 [12] #write_manifest at ./none:0 [inlined]
 [13] #write_env#120 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1564 [inlined]
 [14] write_env at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1561 [inlined]
 [15] #add_or_develop#63(::Array{Base.UUID,1}, ::Symbol, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worke$
/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1173
 [16] #add_or_develop at ./none:0 [inlined]
 [17] #add_or_develop#15(::Symbol, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Contex$
, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:54
 [18] (::getfield(Pkg.API, Symbol("#kw##add_or_develop")))(::NamedTuple{(:mode,),Tuple{Symbol}}, ::typeof(Pkg.API.add_or_develop), ::Pkg.Types.Co$
text, ::Array{Pkg.Types.PackageSpec,1}) at ./none:0
 [19] do_add!(::Dict{Symbol,Any}, ::Array{Pkg.Types.PackageSpec,1}, ::Dict{Symbol,Any}) at /buildworker/worker/package_linux64/build/usr/share/jul
ia/stdlib/v1.1/Pkg/src/REPLMode.jl:659
 [20] #invokelatest#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Any, ::Any, ::Vararg{Any,N} where N) a
t ./essentials.jl:742
 [21] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:741
 [22] do_cmd!(::Pkg.REPLMode.PkgCommand, ::REPL.LineEditREPL) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REP
LMode.jl:561
[23] #do_cmd#30(::Bool, ::Function, ::REPL.LineEditREPL, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/s
rc/REPLMode.jl:536
 [24] do_cmd at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:532 [inlined]
 [25] (::getfield(Pkg.REPLMode, Symbol("##48#51")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{
UInt8,1}}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:967
 [26] #invokelatest#1 at ./essentials.jl:742 [inlined]
 [27] invokelatest at ./essentials.jl:741 [inlined]
 [28] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64
/build/usr/share/julia/stdlib/v1.1/REPL/src/LineEdit.jl:2273
 [29] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/R
EPL.jl:1035
 [30] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:192
 [31] (::getfield(Base, Symbol("##734#736")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:362
 [32] #invokelatest#1 at ./essentials.jl:742 [inlined]
 [33] invokelatest at ./essentials.jl:741 [inlined]
 [34] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:346
 [35] exec_options(::Base.JLOptions) at ./client.jl:284
 [36] _start() at ./client.jl:436
```

Worse, this happened at just the wrong time to wipe out my `Manifest.toml` file.  I think perhaps we should write out to `Manifest.toml.new`, then only when that successfully finishes do we `mv("Manifest.toml.new", "Manifest.toml")`, because losing your entire Manifest is a pretty bad bug; a lot of useful information is encoded into that, for reproducibility purposes.

### PR DESCRIPTION
**Pull request by fredrikekre**
Write out `Project.toml` and `Manifest.toml` to a temporary
`IOBuffer`, before modifying the file on disk, fixes #1202.

### CODE REVIEW

File: src/project.jl [hunk 1]
```diff
@@ -170,12 +170,11 @@ project_key_order(key::String) =
 
 write_project(project::Project, project_file::AbstractString) =
     write_project(destructure(project), project_file)
-write_project(project::Project, io::IO) =
-    write_project(destructure(project), io)
```
Comment (staticfloat) [inline src/project.jl]: So I guess we never call `write_project(::Project, ::IO)`?

Comment (fredrikekre) [reply src/project.jl]: No :)
