### PR TITLE
Replace an `AssertionError` with a more appropriate exception type

### LINKED ISSUE #2535: internal error instantiating an older manifest
With an older Manifest file, I caused Pkg to fail internally with this log:
```
(@v1.6) pkg> activate ~/.julia/dev/BaseBenchmarks/
  Activating environment at `~/.julia/dev/BaseBenchmarks/Project.toml`

(BaseBenchmarks) pkg> instantiate
ERROR: AssertionError: sourcepath !== nothing
Stacktrace:
  [1] is_package_downloaded(ctx::Pkg.Types.Context, pkg::Pkg.Types.PackageSpec)
    @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1784
  [2] #13
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:131 [inlined]
  [3] _all
    @ ./reduce.jl:923 [inlined]
  [4] #all#698
    @ ./reducedim.jl:886 [inlined]
  [5] all
    @ ./reducedim.jl:886 [inlined]
  [6] is_instantiated(ctx::Pkg.Types.Context)
    @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:131
  [7] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1335
  [8] instantiate
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1304 [inlined]
  [9] instantiate(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1300
 [10] instantiate()
    @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1300
 [11] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:405
 [12] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:386
 [13] do_cmd
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:377 [inlined]
 [14] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:550
 [15] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [16] invokelatest
    @ ./essentials.jl:706 [inlined]
 [17] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2441
 [18] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1126
 [19] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:411
```

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #2535 

As @vtjnash points out in https://github.com/JuliaLang/Pkg.jl/issues/2535#issuecomment-828501016:
> `AssertionError` always means the package did something wrong and unexpected.

However, this is not the case here. This assertion will fail in normal operation. For example, it may fail if you take a manifest generated by an older version of Julia and try to use that manifest with a newer version of Julia.

Therefore, we shouldn't use an `AssertionError` here.

This PR changes the exception to a `Pkg.Types.PkgError`, but we could also pick a different exception type.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Bump @vtjnash. Does this address your comment in https://github.com/JuliaLang/Pkg.jl/issues/2535#issuecomment-828501016?

**Comment by DilumAluthge** [comment]
Yeah, the `source_path` function is supposed to return the location of the source code of the given package.

How about doing this instead?

```julia
identifier = pkg.name !== nothing ? pkg.name : pkg.uuid
(sourcepath === nothing) && pkgerror("Could not locate the source code for the $(identifier) package. Are you trying to use a manifest generated by a different version of Julia?")
```

I think the error message is nicer if you print the package name, but the name might be `nothing`, so if the name is `nothing` we can try printing the UUID instead.

**Comment by DilumAluthge** [comment]
> Yeah, the `source_path` function is supposed to return the location of the source code of the given package.
> 
> How about doing this instead?
> 
> ```julia
> identifier = pkg.name !== nothing ? pkg.name : pkg.uuid
> (sourcepath === nothing) && pkgerror("Could not locate the source code for the $(identifier) package. Are you trying to use a manifest generated by a different version of Julia?")
> ```
> 
> I think the error message is nicer if you print the package name, but the name might be `nothing`, so if the name is `nothing` we can try printing the UUID instead.

Alright, I have implemented this change.

**Comment by vtjnash** [comment]
SGTM

File: src/Operations.jl [hunk 1]
```diff
@@ -1702,7 +1702,8 @@ end
 
 function is_package_downloaded(project_file::String, pkg::PackageSpec)
     sourcepath = source_path(project_file, pkg)
-    @assert sourcepath !== nothing
+    identifier = pkg.name !== nothing ? pkg.name : pkg.uuid
+    (sourcepath === nothing) && pkgerror("Could not locate the source code for the $(identifier) package. Are you trying to use a manifest generated by a different version of Julia?")
```
Comment (IanButterworth) [inline src/Operations.jl:1706]:
```suggestion
    (sourcepath === nothing) && pkgerror("Could not locate the source code for the $(identifier) package. This can happen if the manifest was generated by another julia version. Run `import Pkg; Pkg.resolve()` to update the manifest")
```
Perhaps give actionable advice? Worth double-checking the advice to re-resolve fixes it though

Comment (DilumAluthge) [reply src/Operations.jl:1706]: Does this step actually work? I was under the impression that it will still error.

Comment (DilumAluthge) [reply src/Operations.jl:1706]: I'm going to merge this PR now, but if we can confirm that this advice actually does work, then we can edit the error message and add this advice.
