### PR TITLE
tweak the code for getting the registry from PkgServer

### LINKED ISSUE #1622: Big try catch in code for getting the registry from Pkg server
The code:

https://github.com/JuliaLang/Pkg.jl/blob/f78c1e1ad6d4ade6d72ab6b283f8c9b65a879c2a/src/Types.jl#L862-L882

has a very big try catch block.  This could easily disquise typos which might go unnoticed on CI since it will fallback to getting the registry from git. 

It would be better if the try catch could only enclose the actual `download` call, and also perhaps check the type of the exception.

cc @StefanKarpinski

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #1622 and https://github.com/JuliaLang/Pkg.jl/issues/1622#issuecomment-577614170.

### CODE REVIEW

File: src/Types.jl [hunk 1]
```diff
@@ -863,22 +863,24 @@ function pkg_server_registry_url(uuid::UUID)
...
-    hash === nothing ? nothing : "$server/registry/$uuid/$hash"
+    if download_ok
+        for line in eachline(tmp_path)
+            if (m = match(r"^/registry/([^/]+)/([^/]+)$", line)) !== nothing
+                uuid == UUID(m.captures[1]) || continue
+                hash = String(m.captures[2])
+                return "$server/registry/$uuid/$hash"
+            end
+        end
+    end
```
Comment (StefanKarpinski) [inline src/Types.jl]:
```suggestion
    end
    rm(tmp_path, force=true)
```
