### PR TITLE
Fix ~/nested/path expansion

### LINKED ISSUE #1826: Incorrect expansion of ~/nested/paths in Pkg REPL mode
With the following nested directory structure

```
❯ tree ~/foo
/Users/harry/foo
└── bar
    └── baz
```

If I type the following in the REPL in Pkg mode

```
(@v1.4) pkg> dev ~/foo/bar/baz
```

It autocompletes to

```
(@v1.4) pkg> dev /Users/harry/baz/
```

The path is correctly expanded by `Base.expanduser` though

```
julia> expanduser("~/foo/bar/baz")
"/Users/harry/foo/bar/baz"
```

I think the problem is in

https://github.com/JuliaLang/Pkg.jl/blob/a5df9271ac47415ddbc00f1d0ed1643100d803da/src/REPLMode/completions.jl#L41

and is fixed by

```julia
completions = [joinpath(dirname(s), x) for x in completions]
```

### PR DESCRIPTION
**Pull request by harryscholes**
Fixes #1826

### CODE REVIEW

File: src/REPLMode/completions.jl [hunk 1]
```diff
@@ -38,7 +38,7 @@ function complete_local_dir(s, i1, i2)
         if length(completions) == 1 && endswith(joinpath(homedir(), ""), first(completions))
             completions = [joinpath(s, "")]
         else
-            completions = [joinpath(homedir(), x) for x in completions]
+            completions = [joinpath(dirname(s), x) for x in completions]
         end
         return completions, i1:oldi2, true
```
Comment (harryscholes) [inline src/REPLMode/completions.jl:43]: Should this now be `i1:i2`?

**Comment by harryscholes** [comment]
Btw I've added a test and it passes

**Comment by KristofferC** [comment]
Thanks!
