### PR TITLE
Precomp: fix PkgId bug and bad test in circular deps, interrupt faster, add elapsed time, handle missing cache for loaded pkgs, instantiate if not instantiated

### LINKED ISSUE #2149: Aborting precompilation is brittle
For example
```
(@v1) pkg> add Plots
   Resolving package versions...
No Changes to `~/.julia/environments/v1/Project.toml`
No Changes to `~/.julia/environments/v1/Manifest.toml`
Precompiling project... (tip: to disable auto-precompilation set ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0)
  Progress [==================>                      ]  36/81
  ◑ DataStructures
  ◑ IntervalArithmetic
  ◑ Highlights
  ◑ JSON3
  ✓ MethodAnalysis
  ◑ EzXML
^Cfatal: error thrown and no exception handler available.
InterruptException()
jl_mutex_unlock at /home/fredrik/julia-master/src/locks.h:139 [inlined]
jl_task_get_next at /home/fredrik/julia-master/src/partr.c:475
poptask at ./task.jl:744
wait at ./task.jl:752 [inlined]
task_done_hook at ./task.jl:478
_jl_invoke at /home/fredrik/julia-master/src/gf.c:2191 [inlined]
jl_apply_generic at /home/fredrik/julia-master/src/gf.c:2373
jl_apply at /home/fredrik/julia-master/src/julia.h:1690 [inlined]
jl_finish_task at /home/fredrik/julia-master/src/task.c:208
start_task at /home/fredrik/julia-master/src/task.c:832
unknown function (ip: (nil))
```
and Julia crashes.

Another failure mode I have seen is that the cursor dissappears for the rest of that terminal session.

### LINKED ISSUE #2151: Show time spent precompiling
Might be nice to show:

```
173 dependencies successfully precompiled in xxx seconds
```

### LINKED ISSUE #2157: Unstable state where compilecache return successfully for some packages, but generates no .ji files
This issue may need to be moved over to Base, but I thought I'd check that we're not missing something obvious in `Pkg.precompile` first

Sometimes `Pkg.precompile` gets into a state where it thinks `compilecache` is successful, when it hasn't been, and no `.ji` files are produced.

```
(@v1.6) pkg> precompile
Precompiling project...
  Progress [========================================>]  248/248
248 dependencies successfully precompiled in 114 seconds (90 already precompiled)

(@v1.6) pkg> precompile
Precompiling project...
  Progress [========================================>]  59/59
59 dependencies successfully precompiled in 65 seconds (279 already precompiled)

(@v1.6) pkg> precompile
Precompiling project...
  Progress [========================================>]  59/59
59 dependencies successfully precompiled in 66 seconds (279 already precompiled)
```

Each of those 59 dependencies has an empty `compiled/v1.6` dir after completion

If I then go on to load one of the failed packages, the following happens and the dir remains empty

```
julia> using CSV
[ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
[ Info: Skipping precompilation since __precompile__(false). Importing CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b].
[ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
[ Info: Skipping precompilation since __precompile__(false). Importing DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0].
[ Info: Precompiling SortingAlgorithms [a2af1166-a08f-5f64-846c-94a0d3cef48c]
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
[ Info: Skipping precompilation since __precompile__(false). Importing SortingAlgorithms [a2af1166-a08f-5f64-846c-94a0d3cef48c].
[ Info: Precompiling DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8]
┌ Warning: Module OrderedCollections with build ID 485552313728875 is missing from the cache.
│ This may mean OrderedCollections [bac558e1-5e72-5ebc-8fee-abe8a469f55d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1020
[ Info: Skipping precompilation since __precompile__(false). Importing DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8].
```

Unless I'm mistaken, given our setup `compilecache` can't be erroring, so I think  it's a Base issue.

https://github.com/JuliaLang/Pkg.jl/blob/fcf175de737d5eaaca967d840d0c0d2e62547452/src/API.jl#L1120-L1144

### PR DESCRIPTION
**Pull request by ianshmean**
- Fixes a bug in the circular dep suspender that wasn't caught in tests because the `@async` circular dep test wasn't checking for failure, just completion..

- Interrupts faster by leaving in-progress compilecache tasks to finish in background (fixes #2149)

- Add seconds elapsed to report (closes #2151)

- Added handling for when the cache is deleted out from underneath a loaded package, and compilecache doesn't error but returns a `Base.PrecompilableError` (closes #2157)

image

- Instantiate if not instantiated (doesn't noticeably increase no-op, see comment below)

### CODE REVIEW

**Comment by ianshmean** [comment]
@giordano reported that activating a  project that's not instantiated, then calling `precompile` resulted in a hang. So I've added a check for the context being instantiated, and instantiating if needed.

This was a repro for the error. Requires packages to be missing
```
(v1.6) pkg> activate /Users/ian/Documents/GitHub/PkgServerLogAnalysis.jl

(PkgServerLogAnalysis) pkg> precompile
Precompiling project...
  Progress [==================================>      ]  69/83
^C Interrupted: Exiting precompilation...
```
Fixed on this PR
```
(v1.6) pkg> activate /Users/ian/Documents/GitHub/PkgServerLogAnalysis.jl
  Activating environment at `~/Documents/GitHub/PkgServerLogAnalysis.jl/Project.toml`

(PkgServerLogAnalysis) pkg> precompile
   Installed Arpack_jll ─────── v3.5.0+3
   Installed Arpack ─────────── v0.4.0
   Installed Distances ──────── v0.10.0
   Installed NearestNeighbors ─ v0.4.7
   Installed Pluto ──────────── v0.12.4
   Installed Plots ──────────── v1.7.1
   Installed Clustering ─────── v0.14.2
Precompiling project... (tip: to disable auto-precompilation set ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0)
  Progress [========================================>]  118/118
118 dependencies successfully precompiled in 91 seconds
```

After that, the precompile no-op in that project is
```
julia> @time Pkg.precompile()
  0.322914 seconds (890.29 k allocations: 64.414 MiB, 1.59% gc time)
```

**Comment by ianshmean** [comment]
@KristofferC: This absorbed a few different fixes, and should be ready to go. 

I think it should be in pretty good shape now..

File: src/API.jl [hunk 1]
```diff
@@ -916,6 +916,10 @@ end
 precompile(; kwargs...) = precompile(Context(); kwargs...)
 function precompile(ctx::Context; internal_call::Bool=false, kwargs...)
     Context!(ctx; kwargs...)
+    if !Operations.is_instantiated(ctx)
+        Pkg.instantiate(ctx; allow_autoprecomp=false, kwargs...)
```
Comment (KristofferC) [inline src/API.jl:920]: Can't `instantiate` be called directly? If the env is instantiated it should be a no-op?

File: src/API.jl [hunk 2]
```diff
@@ -1161,25 +1175,46 @@ function precompile(ctx::Context; internal_call::Bool=false, kwargs...)
                 end
             end
         end
+        push!(tasks, task)
+    end
+    while !interrupted && any(!istaskdone, tasks)
+        try
+            sleep(0.001)
```
Comment (KristofferC) [inline src/API.jl:1182]: This thing looks pretty weird. Can't this somehow be done in a blocking way instead of spinning on a `sleep`?

File: src/API.jl [hunk 3]
```diff
@@ -1161,25 +1175,46 @@ function precompile(ctx::Context; internal_call::Bool=false, kwargs...)
...
+        catch err
```
Comment (KristofferC) [inline src/API.jl:1183]: What happens with `err` if this is not an `InterruptException`?

File: src/API.jl (hunk 1 above)
Comment (ianshmean) [reply src/API.jl:920]: Yeah, you're right
```
julia> ctx = Pkg.Types.Context();

julia> @time Pkg.Operations.is_instantiated(ctx)
  0.156026 seconds (915.04 k allocations: 69.247 MiB, 8.86% gc time)
true

julia> @time Pkg.Operations.is_instantiated(ctx)
  0.154110 seconds (915.04 k allocations: 69.252 MiB, 7.59% gc time)
true

julia> @time Pkg.instantiate(ctx, allow_autoprecomp = false)
  0.147273 seconds (917.09 k allocations: 69.444 MiB, 3.33% gc time)

julia> @time Pkg.instantiate(ctx, allow_autoprecomp = false)
  0.152403 seconds (917.10 k allocations: 69.454 MiB, 6.80% gc time)
```

File: src/API.jl (hunk 2 above)
Comment (ianshmean) [reply src/API.jl:1182]: There may be something tidier but I couldn't figure one out.
We can't use `@sync` as we want to exit before all the compilecache tasks are done when a `^C` is thrown.
And we can't do a single `wait()` here because we need to check for both `!interrupted && any(!istaskdone, tasks)` and not block the other async tasks

File: src/API.jl (hunk 3 above)
Comment (ianshmean) [reply src/API.jl:1181]: I had thought it was ok because it's just a `sleep`, but I've added a throw for safety

Comment (KristofferC) [reply src/API.jl:1181]: Ah, I see now.

File: src/API.jl [hunk 4]
```diff
@@ -1149,37 +1166,45 @@ function precompile(ctx::Context; internal_call::Bool=false, kwargs...)
                 n_done += 1
                 notify(was_processed[pkg])
             catch err_outer
-                interrupted = true
-                show_report = false
+                handle_interrupt(err)
```
Comment (giordano) [inline src/API.jl:1169]:
```suggestion
                handle_interrupt(err_outer)
```
?

Comment (ianshmean) [reply src/API.jl]: Thanks!

File: src/API.jl (hunk 2 above)
Comment (ianshmean) [reply src/API.jl]: Figured it out. Now updated
