### PR TITLE
Fix codeblock language and prompt in Pkg.status() docstring

### LINKED ISSUE #3954: Weird syntax highlighting in docstrings
Happens on `julia +nightly`. Issue is likely that the stdout output is included in a codeblock (cc @fredrikekre).

image

### PR DESCRIPTION
**Pull request by fatteneder**
Fixes #3954

image

### CODE REVIEW

File: src/Pkg.jl [hunk 1]
```diff
@@ -520,11 +520,14 @@ packages holding them back due to compatibility constraints, or due to compatibi
 As an example, a status output like:
 ```
 pkg> Pkg.status(; outdated=true)
```
Comment (fredrikekre) [inline src/Pkg.jl:522]: This should be a julia prompt then?

Comment (fatteneder) [reply src/Pkg.jl:522]: Julia prompt is `julia-repl`?
Adding this does not highlight anything then.

Comment (fatteneder) [reply src/Pkg.jl]: Now I see what you mean. I fixed it.
