### PR TITLE
Precompile: Throw errors properly, disable auto during `Pkg.test`, remove trailing new line, remember suspensions for projects and after restart

### LINKED ISSUE #2110: Automatic precompilation in testing
I did not investigate this fully but there seems to be two potential issues here:
```
$ pkg st
Status `/tmp/tmp.PatNYm6KXK/Project.toml`
  [50fe2c2e] Bar v0.1.0 `Bar`
  [7876af07] Example v0.5.3

$ pkg test Example
Precompiling project... (tip: to disable auto-precompilation set ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0)
  ✗ Bar
0 dependencies successfully precompiled, 1 errored (1 already precompiled)

PkgError: The following direct dependencies failed to precompile:
  Bar [50fe2c2e-f4b2-4264-9eb4-931c784c76dc]
```

1. Why are we precompiling an env with `Bar` in it? That should not happen since `Bar` is not a dependency of `Example`.
2. We probably should disable the call to `precompile` in testing?

### LINKED ISSUE #2112: New precompile output leaves extra empty line
```
(tmp.UYaWHJxUHJ) pkg> add Example
  Resolving package versions...
Updating `/tmp/tmp.UYaWHJxUHJ/Project.toml`
  [7876af07] + Example v0.5.3
Updating `/tmp/tmp.UYaWHJxUHJ/Manifest.toml`
  [7876af07] + Example v0.5.3
Precompiling project... (tip: to disable auto-precompilation set ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0)
1 dependency successfully precompiled

                                                                  <--- ??
(tmp.UYaWHJxUHJ) pkg> add Example
  Resolving package versions...
No Changes to `/tmp/tmp.UYaWHJxUHJ/Project.toml`
No Changes to `/tmp/tmp.UYaWHJxUHJ/Manifest.toml`

(tmp.UYaWHJxUHJ) pkg>
```

### LINKED ISSUE #2116: Don't retry precompilation for packages that failed unless versions changed
For some reason `BinaryBuilderBase` fails to precompile in my environment currently.
As a result, `Pkg` not tries to precompile it on every Pkg operation, which is quite annoying.

### LINKED ISSUE #2118: duplicate/stuck item in precompile output
After running `precompile` with the attached Project and Manifest, I get:
```
(@v1.6) pkg> precompile
Precompiling project...
  ◐ CUDA
  ◐ GeneralizedGenerated
  ◐ MathOptInterface
  ◓ CUDA
340 dependencies successfully precompiled
```
CUDA is listed twice, plus those four progress lines are stuck there.

Project.toml:
```
[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashCoreComponents = "1b08a953-4be3-4667-9a23-f6ba134464e5"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-e4a2b8b6b400"
DashTable = "1b08a953-4be3-4667-9a23-759fc69216d1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForneyLab = "9fc3f58a-c2cc-5bff-9419-6a294fefdca9"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
HAML = "0bc81568-2411-4001-9bf1-c899fa54f385"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
MiniFB = "cc649173-1898-4bb8-8a16-ca5f88bd87d9"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WithInclude = "3fa0cd96-eef1-5676-8a61-b3b8758b0000"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
x265_jll = "dfaa095f-4041-5dcd-9319-2fabd8486b76"
```

Manifest.toml:
```
# This file is machine-generated - editing it directly is not advised

[[AbstractAlgebra]]
deps = ["InteractiveUtils", "LinearAlgebra", "Markdown", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "8fa03ecf25341ff3e8fb301dba3f41c6fe09952e"
uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
version = "0.10.0"

[[AbstractFFTs]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "051c95d6836228d120f5f4b984dd5aba1624f716"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.5.0"

[[AbstractPlotting]]
deps = ["Animations", "ColorBrewer", "ColorSchemes", "ColorTypes", "Colors", "Contour", "Distributions", "DocStringExtensions", "FFMPEG", "FileIO", "FixedPointNumbers", "Formatting", "FreeType", "FreeTypeAbstraction", "GeometryBasics", "GridLayoutBase", "ImageIO", "IntervalSets", "KernelDensity", "LinearAlgebra", "Markdown", "Match", "Observables", "Packing", "PlotUtils", "Printf", "Random", "Serialization", "Showoff", "SignedDistanceFields", "SparseArrays", "StaticArrays", "Statistics", "StatsBase", "StructArrays", "UnicodeFun"]
git-tree-sha1 = "e15a15bb46333c23f07523fcc5ec26ccbb0a5153"
uuid = "537997a7-5e4e-5d89-9595-2241ea00577e"
version = "0.12.15"

[[AbstractTrees]]
deps = ["Markdown"]
git-tree-sha1 = "33e450545eaf7699da1a6e755f9ea65f14077a45"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.3.3"

[[Adapt]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "42c42f2221906892ceb765dbcb1a51deeffd86d7"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "2.3.0"

[[AlgebraOfGraphics]]
deps = ["AbstractPlotting", "CategoricalArrays", "GLM", "KernelDensity", "Loess", "NamedDims", "Observables", "StatsBase", "StructArrays", "Tables"]
git-tree-sha1 = "78b30376771f1a498e84d2c85d435b20e93c04c9"
uuid = "cbdf2221-f076-402e-a563-3d30da359d67"
version = "0.1.2"

[[Animations]]
deps = ["Colors"]
git-tree-sha1 = "e81c509d2c8e49592413bfb0bb3b08150056c79d"
uuid = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
version = "0.4.1"

[[ApproxFun]]
deps = ["AbstractFFTs", "ApproxFunBase", "ApproxFunFourier", "ApproxFunOrthogonalPolynomials", "ApproxFunSingularities", "Calculus", "DomainSets", "DualNumbers", "FFTW", "FastTransforms", "LinearAlgebra", "RecipesBase", "Reexport"]
git-tree-sha1 = "ec4b8ad650e0384c35f670fcfcbc8c30f94165fa"
uuid = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
version = "0.12.2"

[[ApproxFunBase]]
deps = ["AbstractFFTs", "BandedMatrices", "BlockArrays", "BlockBandedMatrices", "Calculus", "DSP", "DomainSets", "DualNumbers", "FFTW", "FastGaussQuadrature", "FillArrays", "InfiniteArrays", "IntervalSets", "LazyArrays", "LinearAlgebra", "LowRankApprox", "SparseArrays", "SpecialFunctions", "StaticArrays", "Statistics", "Test", "ToeplitzMatrices"]
git-tree-sha1 = "c8dfac98702802cbe9ec974902063636cdeab8ec"
uuid = "fbd15aa5-315a-5a7d-a8a4-24992e37be05"
version = "0.3.9"

[[ApproxFunFourier]]
deps = ["AbstractFFTs", "ApproxFunBase", "DomainSets", "FFTW", "FastTransforms", "InfiniteArrays", "IntervalSets", "LinearAlgebra", "Reexport"]
git-tree-sha1 = "6ea501542db56ac87d0c7f716a0bea23cfdf0414"
uuid = "59844689-9c9d-51bf-9583-5b794ec66d30"
version = "0.2.5"

[[ApproxFunOrthogonalPolynomials]]
deps = ["AbstractFFTs", "ApproxFunBase", "BandedMatrices", "BlockArrays", "BlockBandedMatrices", "DomainSets", "FFTW", "FastGaussQuadrature", "FastTransforms", "FillArrays", "IntervalSets", "LinearAlgebra", "Reexport", "SpecialFunctions", "Statistics"]
git-tree-sha1 = "7ad6fc331a41bd1d7b645d999e4b30438662a65e"
uuid = "b70543e2-c0d9-56b8-a290-0d4d6d4de211"
version = "0.3.5"

[[ApproxFunSingularities]]
deps = ["ApproxFunBase", "ApproxFunOrthogonalPolynomials", "DomainSets", "IntervalSets", "LinearAlgebra", "Reexport", "Statistics"]
git-tree-sha1 = "f81dc4a9f09547b280183ebbdc79d2d91ff94c02"
uuid = "f8fcb915-6b99-5be2-b79a-d6dbef8e6e7e"
version = "0.2.0"

[[ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"

[[ArnoldiMethod]]
deps = ["DelimitedFiles", "LinearAlgebra", "Random", "SparseArrays", "StaticArrays", "Test"]
git-tree-sha1 = "2b6845cea546604fb4dca4e31414a6a59d39ddcd"
uuid = "ec485272-7323-5ecc-a04f-4719b315124d"
version = "0.0.4"

[[ArrayInterface]]
deps = ["LinearAlgebra", "Requires", "SparseArrays"]
git-tree-sha1 = "22a41da12a13baf9bd22f16fb866086c33ad7835"
uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
version = "2.13.5"

[[ArrayLayouts]]
deps = ["Compat", "FillArrays", "LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "d6f1ecde467019346f7601fb2ee58cb2bc60d121"
uuid = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
version = "0.4.8"

[[Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[AxisAlgorithms]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "WoodburyMatrices"]
git-tree-sha1 = "a4d07a1c313392a77042855df46c5f534076fab9"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "1.0.0"

[[AxisArrays]]
deps = ["Dates", "IntervalSets", "IterTools", "RangeArrays"]
git-tree-sha1 = "f31f50712cbdf40ee8287f0443b57503e34122ef"
uuid = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
version = "0.4.3"

[[BandedMatrices]]
deps = ["ArrayLayouts", "Compat", "FillArrays", "LinearAlgebra", "Random", "SparseArrays"]
git-tree-sha1 = "da346dce894b95576e55bca5ca768053978293c3"
uuid = "aae01518-5342-5314-be14-df237901396f"
version = "0.15.22"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BenchmarkTools]]
deps = ["JSON", "Logging", "Printf", "Statistics", "UUIDs"]
git-tree-sha1 = "9e62e66db34540a0c919d72172cc2f642ac71260"
uuid = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
version = "0.5.0"

[[BinaryProvider]]
deps = ["Libdl", "Logging", "SHA"]
git-tree-sha1 = "ecdec412a9abc8db54c0efc5548c64dfce072058"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.10"

[[BitIntegers]]
deps = ["Random"]
git-tree-sha1 = "f0853a9d2cf2cf4f9fbd98c6e19ff1627e65a9a7"
uuid = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
version = "0.2.4"

[[BlockArrays]]
deps = ["ArrayLayouts", "Compat", "FillArrays", "LinearAlgebra"]
git-tree-sha1 = "991ebcb0a29450b861b5521c3217b5444f16cc2a"
uuid = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
version = "0.12.13"

[[BlockBandedMatrices]]
deps = ["ArrayLayouts", "BandedMatrices", "BlockArrays", "Distributed", "FillArrays", "LinearAlgebra", "MatrixFactorizations", "Pkg", "SharedArrays", "SparseArrays", "Statistics"]
git-tree-sha1 = "325f79284f3c8a03287f861dfb9f330341972c2c"
uuid = "ffab5731-97b5-5995-9138-79e8c1846df0"
version = "0.9.4"

[[Bzip2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c3598e525718abcc440f69cc6d5f60dda0a1b61e"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.6+5"

[[CEnum]]
git-tree-sha1 = "215a9aa4a1f23fbd05b92769fdd62559488d70e9"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.1"

[[CRlibm]]
deps = ["Libdl"]
git-tree-sha1 = "9d1c22cff9c04207f336b8e64840d0bd40d86e0e"
uuid = "96374032-68de-5a5b-8d9e-752f78720389"
version = "0.8.0"

[[CSV]]
deps = ["CategoricalArrays", "DataFrames", "Dates", "Mmap", "Parsers", "PooledArrays", "SentinelArrays", "Tables", "Unicode"]
git-tree-sha1 = "a390152e6850405a48ca51bd7ca33d11a21d6230"
uuid = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
version = "0.7.7"

[[CUDA]]
deps = ["AbstractFFTs", "Adapt", "BinaryProvider", "CEnum", "DataStructures", "ExprTools", "GPUArrays", "GPUCompiler", "LLVM", "Libdl", "LinearAlgebra", "Logging", "MacroTools", "NNlib", "Pkg", "Printf", "Random", "Reexport", "Requires", "SparseArrays", "Statistics", "TimerOutputs"]
git-tree-sha1 = "83bfd180e2f842f6d4ee315a6db8665e9aa0c19b"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "1.3.3"

[[Cairo]]
deps = ["Cairo_jll", "Colors", "Glib_jll", "Graphics", "Libdl", "Pango_jll"]
git-tree-sha1 = "d0b3f8b4ad16cb0a2988c6788646a5e6a17b6b1b"
uuid = "159f3aea-2a34-519c-b102-8c37f9878175"
version = "1.0.5"

[[Cairo_jll]]
deps = ["Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "c6c9c288df5ad1e6534c9dacd9972482c1eb838c"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.0+5"

[[Calculus]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "f641eb0a4f00c343bbc32346e1217b86f3ce9dad"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.5.1"

[[CanonicalTraits]]
deps = ["MLStyle"]
git-tree-sha1 = "fe3d23a57c0c9d9b99d7e65890a36c3de6b14906"
uuid = "a603d957-0e48-4f86-8fbd-0b7bc66df689"
version = "0.2.3"

[[CatIndices]]
deps = ["CustomUnitRanges", "OffsetArrays"]
git-tree-sha1 = "0c91e4fcda51bbd881c5d49ef784460750abcac0"
uuid = "aafaddc9-749c-510e-ac4f-586e18779b91"
version = "0.2.1"

[[CategoricalArrays]]
deps = ["DataAPI", "Future", "JSON", "Missings", "Printf", "Statistics", "StructTypes", "Unicode"]
git-tree-sha1 = "2ac27f59196a68070e132b25713f9a5bbc5fa0d2"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.8.3"

[[ChainRules]]
deps = ["ChainRulesCore", "LinearAlgebra", "Random", "Reexport", "Requires", "Statistics"]
git-tree-sha1 = "41f40d33dfbb246a2f5a6a7739006bf371aa3e4f"
uuid = "082447d4-558c-5d27-93f4-14fc19e9eca2"
version = "0.7.23"

[[ChainRulesCore]]
deps = ["LinearAlgebra", "MuladdMacro"]
git-tree-sha1 = "213b81305993a9711d105fbdf5bce8e6dfd36ecf"
uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
version = "0.9.15"

[[CodeTracking]]
deps = ["InteractiveUtils", "UUIDs"]
git-tree-sha1 = "ce725fcc331618c422e5561a5183baab6a00482c"
uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
version = "1.0.4"

[[CodecBzip2]]
deps = ["Bzip2_jll", "Libdl", "TranscodingStreams"]
git-tree-sha1 = "2e62a725210ce3c3c2e1a3080190e7ca491f18d7"
uuid = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
version = "0.7.2"

[[CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "ded953804d019afa9a3f98981d99b33e3db7b6da"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.0"

[[ColorBrewer]]
deps = ["Colors", "JSON", "Test"]
git-tree-sha1 = "61c5334f33d91e570e1d0c3eb5465835242582c4"
uuid = "a2cac450-b92f-5266-8821-25eda20663c8"
version = "0.4.0"

[[ColorSchemes]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "Random", "StaticArrays"]
git-tree-sha1 = "5d472aa8908568bc198564db06983913a6c2c8e7"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.10.1"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "4bffea7ed1a9f0f3d1a131bbcd4b925548d75288"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.10.9"

[[ColorVectorSpace]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "LinearAlgebra", "SpecialFunctions", "Statistics", "StatsBase"]
git-tree-sha1 = "2ae827d936fa9d8e00dd5166563499c07c5672c5"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.8.6"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Reexport"]
git-tree-sha1 = "008d6bc68dea6beb6303fdc37188cb557391ebf2"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.4"

[[Combinatorics]]
git-tree-sha1 = "08c8b6831dc00bfea825826be0bc8336fc369860"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "1.0.2"

[[CommonSubexpressions]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "7b8a93dba8af7e3b42fecabf646260105ac373f7"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.3.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "SHA", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "f76e41cf110de7176a657c72409e722cfc86fbb6"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "3.20.0"

[[CompilerSupportLibraries_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7c4f882c41faa72118841185afc58a2eb00ef612"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "0.3.3+0"

[[Compose]]
deps = ["Base64", "Colors", "DataStructures", "Dates", "IterTools", "JSON", "LinearAlgebra", "Measures", "Printf", "Random", "Requires", "Statistics", "UUIDs"]
git-tree-sha1 = "a2b4df8e2dc688f2d63b5cfcc00c773218fa9e7f"
uuid = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
version = "0.9.1"

[[ComputationalResources]]
git-tree-sha1 = "52cb3ec90e8a8bea0e62e275ba577ad0f74821f7"
uuid = "ed09eef8-17a6-5b46-8889-db040fac31e3"
version = "0.3.2"

[[ConsoleProgressMonitor]]
deps = ["Logging", "ProgressMeter"]
git-tree-sha1 = "3ab7b2136722890b9af903859afcf457fa3059e8"
uuid = "88cd18e8-d9cc-4ea6-8889-5259c0d15c8b"
version = "0.1.2"

[[ConstructionBase]]
git-tree-sha1 = "a2a6a5fea4d6f730ec4c18a76d27ec10e8ec1c50"
uuid = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
version = "1.0.0"

[[Contour]]
deps = ["StaticArrays"]
git-tree-sha1 = "d05a3a25b762720d40246d5bedf518c9c2614ef5"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.5"

[[CoordinateTransformations]]
deps = ["LinearAlgebra", "StaticArrays"]
git-tree-sha1 = "c230b1d94db9fdd073168830437e64b9db627fcb"
uuid = "150eb455-5306-5404-9cee-2592286d6298"
version = "0.6.0"

[[CoupledFields]]
deps = ["LinearAlgebra", "Statistics", "StatsBase"]
git-tree-sha1 = "6c9671364c68c1158ac2524ac881536195b7e7bc"
uuid = "7ad07ef1-bdf2-5661-9d2b-286fd4296dac"
version = "0.2.0"

[[CpuId]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "f0464e499ab9973b43c20f8216d088b61fda80c6"
uuid = "adafc99b-e345-5852-983c-f28acb93d879"
version = "0.2.2"

[[Crayons]]
git-tree-sha1 = "3f71217b538d7aaee0b69ab47d9b7724ca8afa0d"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.0.4"

[[Cthulhu]]
deps = ["CodeTracking", "FoldingTrees", "InteractiveUtils", "REPL", "UUIDs", "Unicode"]
git-tree-sha1 = "7312835f32e8dfb2ed49c869e102c7d5fa121614"
uuid = "f68482b8-f384-11e8-15f7-abe071a5a75f"
version = "1.2.2"

[[CustomUnitRanges]]
git-tree-sha1 = "0d42a23be3acfb3c58569b28ed3ab8bd67af5ced"
uuid = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
version = "1.0.0"

[[DSP]]
deps = ["FFTW", "IterTools", "LinearAlgebra", "Polynomials", "Random", "Reexport", "SpecialFunctions", "Statistics"]
git-tree-sha1 = "83ba258fd937d7b329b6d0ade7a01b3ceea45a3c"
uuid = "717857b8-e6f2-59f4-9121-6e50c889abd2"
version = "0.6.8"

[[Dash]]
git-tree-sha1 = "38dacaba1657192e5bc4505df452a4bf38990e02"
repo-rev = "dev"
repo-url = "https://github.com/plotly/Dash.jl.git"
uuid = "1b08a953-4be3-4667-9a23-3db579824955"
version = "0.1.3"

    [Dash.deps]
    CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
    DashBase = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"
    DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
    DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
    DashTable = "1b08a953-4be3-4667-9a23-f0e2ba4deb9a"
    DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
    HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
    JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
    JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
    MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
    PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
    Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
    UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[DashBase]]
deps = ["JSON2", "Test"]
git-tree-sha1 = "fc7632ba6b4f1c085620870142114f428f51eff0"
uuid = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"
version = "0.1.0"

[[DashCoreComponents]]
deps = ["DashBase"]
git-tree-sha1 = "34e6fdd283c7c5b03d5a8ab05fc9a0ca3ce9700d"
uuid = "1b08a953-4be3-4667-9a23-9da06441d987"
version = "1.12.0"
[[DashCoreComponents]]
deps = ["Dash"]
git-tree-sha1 = "9b1686f7216acaace13539b36a032d6a5e765336"
repo-rev = "jl"
repo-url = "https://github.com/plotly/dash-core-components.git"
uuid = "1b08a953-4be3-4667-9a23-f6ba134464e5"
version = "1.4.0"

[[DashHtmlComponents]]
deps = ["DashBase"]
git-tree-sha1 = "d4f6dd88a5eb25916f9d3eb0c4b49fdb14b4392c"
uuid = "1b08a953-4be3-4667-9a23-24100242a84a"
version = "1.1.1"
[[DashHtmlComponents]]
deps = ["Dash"]
git-tree-sha1 = "1c78a8db0ceecc81bf2ea82ba14bfebc17c6c74b"
repo-rev = "jl"
repo-url = "https://github.com/plotly/dash-html-components.git"
uuid = "1b08a953-4be3-4667-9a23-e4a2b8b6b400"
version = "1.0.1"

[[DashTable]]
deps = ["Dash"]
git-tree-sha1 = "cac8a2c0ab80b59188bf620520ba576858d38cca"
repo-rev = "jl"
repo-url = "https://github.com/plotly/dash-table.git"
uuid = "1b08a953-4be3-4667-9a23-759fc69216d1"
version = "4.7.0"
[[DashTable]]
deps = ["DashBase"]
git-tree-sha1 = "3c289159c57149f9d6f9039abfe842ea6d3ff2c4"
uuid = "1b08a953-4be3-4667-9a23-f0e2ba4deb9a"
version = "4.10.1"

[[DataAPI]]
git-tree-sha1 = "176e23402d80e7743fc26c19c681bfb11246af32"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.3.0"

[[DataFrames]]
deps = ["CategoricalArrays", "Compat", "DataAPI", "Future", "InvertedIndices", "IteratorInterfaceExtensions", "Missings", "PooledArrays", "Printf", "REPL", "Reexport", "SortingAlgorithms", "Statistics", "TableTraits", "Tables", "Unicode"]
git-tree-sha1 = "ecd850f3d2b815431104252575e7307256121548"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.21.8"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "88d48e133e6d3dd68183309877eac74393daa7eb"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.17.20"

[[DataValueInterfaces]]
git-tree-sha1 = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464"
version = "1.0.0"

[[DataValues]]
deps = ["DataValueInterfaces", "Dates"]
git-tree-sha1 = "d88a19299eba280a6d062e135a43f00323ae70bf"
uuid = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
version = "0.4.13"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Debugger]]
deps = ["CodeTracking", "Crayons", "Highlights", "InteractiveUtils", "JuliaInterpreter", "Markdown", "REPL"]
git-tree-sha1 = "c37eca3eff2657c700f32e05500215feac886dcf"
uuid = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
version = "0.6.6"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffEqBase]]
deps = ["ArrayInterface", "ChainRulesCore", "ConsoleProgressMonitor", "DataStructures", "Distributed", "DocStringExtensions", "FunctionWrappers", "IterativeSolvers", "IteratorInterfaceExtensions", "LabelledArrays", "LinearAlgebra", "Logging", "LoggingExtras", "MuladdMacro", "Parameters", "Printf", "ProgressLogging", "RecipesBase", "RecursiveArrayTools", "RecursiveFactorization", "Requires", "Roots", "SparseArrays", "StaticArrays", "Statistics", "SuiteSparse", "TableTraits", "TerminalLoggers", "TreeViews", "ZygoteRules"]
git-tree-sha1 = "4dde9a142bc3780f0216e564673f477ec6f6a6df"
uuid = "2b5f629d-d688-5b77-993f-72d75c75574e"
version = "6.44.3"

[[DiffEqJump]]
deps = ["ArrayInterface", "Compat", "DataStructures", "DiffEqBase", "FunctionWrappers", "LinearAlgebra", "PoissonRandom", "Random", "RandomNumbers", "RecursiveArrayTools", "StaticArrays", "TreeViews", "UnPack"]
git-tree-sha1 = "97c44c5f94827bb4605e4c72b652629a9d6d10d4"
uuid = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
version = "6.10.0"

[[DiffResults]]
deps = ["StaticArrays"]
git-tree-sha1 = "da24935df8e0c6cf28de340b958f6aac88eaa0cc"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "1.0.2"

[[DiffRules]]
deps = ["NaNMath", "Random", "SpecialFunctions"]
git-tree-sha1 = "eb0c34204c8410888844ada5359ac8b96292cfd1"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "1.0.1"

[[Distances]]
deps = ["LinearAlgebra", "Statistics"]
git-tree-sha1 = "a5b88815e6984e9f3256b6ca0dc63109b16a506f"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.9.2"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Distributions]]
deps = ["FillArrays", "LinearAlgebra", "PDMats", "Printf", "QuadGK", "Random", "SparseArrays", "SpecialFunctions", "StaticArrays", "Statistics", "StatsBase", "StatsFuns"]
git-tree-sha1 = "501c11d708917ca09ce357bed163dbaf0f30229f"
uuid = "31c24e10-a181-5473-b8eb-7969acd0382f"
version = "0.23.12"

[[DocStringExtensions]]
deps = ["LibGit2", "Markdown", "Pkg", "Test"]
git-tree-sha1 = "50ddf44c53698f5e784bbebb3f4b21c5807401b1"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.8.3"

[[Documenter]]
deps = ["Base64", "Dates", "DocStringExtensions", "InteractiveUtils", "JSON", "LibGit2", "Logging", "Markdown", "REPL", "Test", "Unicode"]
git-tree-sha1 = "fb1ff838470573adc15c71ba79f8d31328f035da"
uuid = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
version = "0.25.2"

[[DomainSets]]
deps = ["IntervalSets", "LinearAlgebra", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "7ba497e98b4d58d0b673c800957a2884a3b5d798"
uuid = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
version = "0.4.1"

[[DualNumbers]]
deps = ["Calculus", "LinearAlgebra", "NaNMath", "SpecialFunctions", "Test"]
git-tree-sha1 = "e178a6768dad879ff1abfc1c612406856bb06ce0"
uuid = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
version = "0.6.2"

[[EarCut_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "eabac56550a7d7e0be499125673fbff560eb8b20"
uuid = "5ae413db-bbd1-5e63-b57d-d24a61df00f5"
version = "2.1.5+0"

[[EllipsisNotation]]
git-tree-sha1 = "65dad386e877850e6fce4fc77f60fe75a468ce9d"
uuid = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
version = "0.4.0"

[[ErrorfreeArithmetic]]
git-tree-sha1 = "d6863c556f1142a061532e79f611aa46be201686"
uuid = "90fa49ef-747e-5e6f-a989-263ba693cf1a"
version = "0.5.2"

[[Expat_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "0a4e4402a91b0761c1de961f94204da5e306a4f3"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.7+5"

[[ExprTools]]
git-tree-sha1 = "7fce513fcda766962ff67c5596cb16c463dfd371"
uuid = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
version = "0.1.2"

[[EzXML]]
deps = ["Printf", "XML2_jll"]
git-tree-sha1 = "0fa3b52a04a4e210aeb1626def9c90df3ae65268"
uuid = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
version = "1.1.0"

[[FFMPEG]]
deps = ["FFMPEG_jll", "x264_jll"]
git-tree-sha1 = "9a73ffdc375be61b0e4516d83d880b265366fe1f"
uuid = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
version = "0.4.0"

[[FFMPEG_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "JLLWrappers", "LAME_jll", "LibVPX_jll", "Libdl", "Ogg_jll", "OpenSSL_jll", "Opus_jll", "Pkg", "Zlib_jll", "libass_jll", "libfdk_aac_jll", "libvorbis_jll", "x264_jll", "x265_jll"]
git-tree-sha1 = "3cc57ad0a213808473eafef4845a74766242e05f"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
version = "4.3.1+4"

[[FFTViews]]
deps = ["CustomUnitRanges", "FFTW"]
git-tree-sha1 = "70a0cfd9b1c86b0209e38fbfe6d8231fd606eeaf"
uuid = "4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd"
version = "0.3.1"

[[FFTW]]
deps = ["AbstractFFTs", "FFTW_jll", "IntelOpenMP_jll", "Libdl", "LinearAlgebra", "MKL_jll", "Reexport"]
git-tree-sha1 = "8b7c16b56936047ca41bf25effa137ae0b381ae8"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "1.2.4"

[[FFTW_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "6c975cd606128d45d1df432fb812d6eb10fee00b"
uuid = "f5851436-0d7a-5f13-b9de-f02708fd171a"
version = "3.3.9+5"

[[FastGaussQuadrature]]
deps = ["LinearAlgebra", "SpecialFunctions"]
git-tree-sha1 = "3c73b2165822a0e1c4cc576d925c47d50be55c3d"
uuid = "442a2c76-b920-505d-bb47-c5924d526838"
version = "0.4.3"

[[FastRounding]]
deps = ["ErrorfreeArithmetic", "Test"]
git-tree-sha1 = "224175e213fd4fe112db3eea05d66b308dc2bf6b"
uuid = "fa42c844-2597-5d31-933b-ebd51ab2693f"
version = "0.2.0"

[[FastTransforms]]
deps = ["AbstractFFTs", "ArrayLayouts", "BinaryProvider", "DSP", "FFTW", "FastGaussQuadrature", "FastTransforms_jll", "FillArrays", "Libdl", "LinearAlgebra", "Reexport", "SpecialFunctions", "Test", "ToeplitzMatrices"]
git-tree-sha1 = "3788b3c7550abd31e98147a3ad944b5e2f727be2"
uuid = "057dd010-8810-581a-b7be-e3fc3b93f78c"
version = "0.10.2"

[[FastTransforms_jll]]
deps = ["CompilerSupportLibraries_jll", "FFTW_jll", "Libdl", "MPFR_jll", "OpenBLAS_jll", "Pkg"]
git-tree-sha1 = "052e907d31ab38c1a72db86b1c643afe5ef83f6e"
uuid = "34b6f7d7-08f9-5794-9e10-3819e4c7e49a"
version = "0.3.3+0"

[[FileIO]]
deps = ["Pkg"]
git-tree-sha1 = "992b4aeb62f99b69fcf0cb2085094494cc05dfb3"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.4.3"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[FillArrays]]
deps = ["LinearAlgebra", "Random", "SparseArrays"]
git-tree-sha1 = "502b3de6039d5b78c76118423858d981349f3823"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "0.9.7"

[[FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[Flux]]
deps = ["AbstractTrees", "Adapt", "CUDA", "CodecZlib", "Colors", "DelimitedFiles", "Functors", "Juno", "LinearAlgebra", "MacroTools", "NNlib", "Pkg", "Printf", "Random", "Reexport", "SHA", "Statistics", "StatsBase", "Test", "ZipFile", "Zygote"]
git-tree-sha1 = "ceb09ce8510ef31fd86a791bbd0e1d72a60f27d7"
uuid = "587475ba-b771-5e3f-ad9e-33799f191a9c"
version = "0.11.1"

[[FoldingTrees]]
deps = ["AbstractTrees", "REPL"]
git-tree-sha1 = "e0c730b2d920d29edf8c381695e16c0a28055466"
uuid = "1eca21be-9b9b-4ed8-839a-6d8ae26b1781"
version = "1.0.1"

[[Fontconfig_jll]]
deps = ["Bzip2_jll", "Expat_jll", "FreeType2_jll", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "d130ffccfecaa5f53c9338a76dd165b6c3a4dd5b"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.1+13"

[[Formatting]]
deps = ["Printf"]
git-tree-sha1 = "a0c901c29c0e7c763342751c0a94211d56c0de5c"
uuid = "59287772-0a20-5a39-b81b-1366585eb4c0"
version = "0.4.1"

[[ForneyLab]]
deps = ["Base64", "Documenter", "ForwardDiff", "InteractiveUtils", "LinearAlgebra", "Printf", "Random", "SparseArrays", "SpecialFunctions", "Statistics", "StatsBase", "StatsFuns", "Test"]
git-tree-sha1 = "adff2030a779e2307a85867c3dc7a50f042e4bd6"
uuid = "9fc3f58a-c2cc-5bff-9419-6a294fefdca9"
version = "0.11.1"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "NaNMath", "Random", "SpecialFunctions", "StaticArrays"]
git-tree-sha1 = "1d090099fb82223abc48f7ce176d3f7696ede36d"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.10.12"

[[Franklin]]
deps = ["Dates", "DelimitedFiles", "DocStringExtensions", "ExprTools", "FranklinTemplates", "HTTP", "Literate", "LiveServer", "Logging", "Markdown", "NodeJS", "OrderedCollections", "Pkg", "REPL", "Random"]
git-tree-sha1 = "78bb9cd75d59f87325421e661b607068b353b9d7"
uuid = "713c75ef-9fc9-4b05-94a9-213340da978e"
version = "0.10.3"

[[FranklinTemplates]]
git-tree-sha1 = "9f533d5a42cb49fb7ab13bb5797b5b100e2150b7"
uuid = "3a985190-f512-4703-8d38-2a7944ed5916"
version = "0.7.4"

[[FreeType]]
deps = ["CEnum", "FreeType2_jll"]
git-tree-sha1 = "d5e296dea44f9cfb8cc83681aa3db367e0cbfd4f"
uuid = "b38be410-82b0-50bf-ab77-7b57e271db43"
version = "3.0.1"

[[FreeType2_jll]]
deps = ["Artifacts", "Bzip2_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "cbd58c9deb1d304f5a245a0b7eb841a2560cfec6"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.1+5"

[[FreeTypeAbstraction]]
deps = ["ColorVectorSpace", "Colors", "FreeType", "GeometryBasics", "StaticArrays"]
git-tree-sha1 = "f45aae9cfc9019b6c1fa86dfc5b97250510a9d0c"
uuid = "663a7486-cb36-511b-a19d-713bb74d65c9"
version = "0.8.1"

[[FriBidi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0d20aed5b14dd4c9a2453c1b601d08e1149679cc"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.5+6"

[[FunctionWrappers]]
git-tree-sha1 = "e4813d187be8c7b993cb7f85cbf2b7bfbaadc694"
uuid = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
version = "1.1.1"

[[Functors]]
deps = ["MacroTools"]
git-tree-sha1 = "f40adc6422f548176bb4351ebd29e4abf773040a"
uuid = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
version = "0.1.0"

[[Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[GLFW]]
deps = ["GLFW_jll"]
git-tree-sha1 = "1d52b85c487f130df5b2ab21af35034bf3285916"
uuid = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
version = "3.4.0"

[[GLFW_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libglvnd_jll", "Pkg", "Xorg_libXcursor_jll", "Xorg_libXi_jll", "Xorg_libXinerama_jll", "Xorg_libXrandr_jll"]
git-tree-sha1 = "a1bbf700b5388bffc3d882f4f4d625cf1c714fd7"
uuid = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
version = "3.3.2+1"

[[GLM]]
deps = ["Distributions", "LinearAlgebra", "Printf", "Random", "Reexport", "SparseArrays", "SpecialFunctions", "Statistics", "StatsBase", "StatsFuns", "StatsModels"]
git-tree-sha1 = "11d47ad2699a26d5557e265a2acf3e5c3799e83d"
uuid = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
version = "1.3.10"

[[GLMakie]]
deps = ["AbstractPlotting", "ColorTypes", "Colors", "FileIO", "FixedPointNumbers", "FreeTypeAbstraction", "GLFW", "GeometryBasics", "LinearAlgebra", "Markdown", "MeshIO", "ModernGL", "Observables", "Printf", "Serialization", "ShaderAbstractions", "StaticArrays"]
git-tree-sha1 = "1b2b9f939cbdcfa64e4f9a03601581a337c805b2"
uuid = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
version = "0.1.13"

[[GLPK]]
deps = ["BinaryProvider", "GLPK_jll", "Libdl", "MathOptInterface", "SparseArrays"]
git-tree-sha1 = "86573ecb852e303b209212046af44871f1c0e49c"
uuid = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
version = "0.13.0"

[[GLPKMathProgInterface]]
deps = ["GLPK", "LinearAlgebra", "MathProgBase", "SparseArrays"]
git-tree-sha1 = "dcca815a687d8f398c8fc701c3796a36ef6b73a5"
uuid = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
version = "0.5.0"

[[GLPK_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "ccc855de74292e478d4278e3a6fdd8212f75e81e"
uuid = "e8aa6df9-e6ca-548a-97ff-1f85fc5b8b98"
version = "4.64.0+0"

[[GMP_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7e8752aa0c4a0fdc55b7a5a338a9b14a74def062"
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version = "6.2.0+2"

[[GPUArrays]]
deps = ["AbstractFFTs", "Adapt", "LinearAlgebra", "Printf", "Random", "Serialization"]
git-tree-sha1 = "da6398282abd2a8c0dc3e55b49d984fcc2c582e5"
uuid = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
version = "5.2.1"

[[GPUCompiler]]
deps = ["DataStructures", "InteractiveUtils", "LLVM", "Libdl", "TimerOutputs", "UUIDs"]
git-tree-sha1 = "05097d81898c527e3bf218bb083ad0ead4378e5f"
uuid = "61eb1bfa-7361-4325-ad38-22787b887f55"
version = "0.6.1"

[[GR]]
deps = ["Base64", "DelimitedFiles", "HTTP", "JSON", "LinearAlgebra", "Printf", "Random", "Serialization", "Sockets", "Test", "UUIDs"]
git-tree-sha1 = "cd0f34bd097d4d5eb6bbe01778cf8a7ed35f29d9"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.52.0"

[[Gadfly]]
deps = ["Base64", "CategoricalArrays", "Colors", "Compose", "Contour", "CoupledFields", "DataStructures", "Dates", "Distributions", "DocStringExtensions", "Hexagons", "IndirectArrays", "IterTools", "JSON", "Juno", "KernelDensity", "LinearAlgebra", "Loess", "Measures", "Printf", "REPL", "Random", "Requires", "Showoff", "Statistics"]
git-tree-sha1 = "fce23cb26b95dd5b3b0fbc0d3e721a9a14620e5e"
uuid = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
version = "1.3.1"

[[GeneralizedGenerated]]
deps = ["CanonicalTraits", "DataStructures", "JuliaVariables", "MLStyle"]
git-tree-sha1 = "50e0ed8fbcd56ae2e65b9aa73394f20b30269b2d"
uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
version = "0.2.7"

[[GeometryBasics]]
deps = ["EarCut_jll", "IterTools", "LinearAlgebra", "StaticArrays", "StructArrays", "Tables"]
git-tree-sha1 = "876a906eab3be990fdcbfe1e43bb3a76f4776f72"
uuid = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
version = "0.3.3"

[[GeometryTypes]]
deps = ["ColorTypes", "FixedPointNumbers", "LinearAlgebra", "StaticArrays"]
git-tree-sha1 = "34bfa994967e893ab2f17b864eec221b3521ba4d"
uuid = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
version = "0.8.3"

[[Gettext_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "922315c1eb4e5072b9994fc47072d0351906fe4c"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.20.1+6"

[[Glib_jll]]
deps = ["Gettext_jll", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "10f579c2365338cc1773d60faeb6c9f88ea8a7b3"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.59.0+3"

[[Graphics]]
deps = ["Colors", "LinearAlgebra", "NaNMath"]
git-tree-sha1 = "45d684ead5b65c043ad46bd5be750d61c39d7ef8"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "1.0.2"

[[Graphite2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7e4edd2a8848722b0588a154a08fb1990c62d751"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.13+3"

[[GridLayoutBase]]
deps = ["GeometryBasics", "Match", "Observables"]
git-tree-sha1 = "0c4c647f08d0b36306316cd6b2e3565b69699c29"
uuid = "3955a311-db13-416c-9275-1d80ed98e5e9"
version = "0.3.7"

[[Grisu]]
git-tree-sha1 = "03d381f65183cb2d0af8b3425fde97263ce9a995"
uuid = "42e2da0e-8278-4e71-bc24-59509adca0fe"
version = "1.0.0"

[[HAML]]
deps = ["DataStructures", "Markdown", "Requires"]
git-tree-sha1 = "071463272a28d3945d036f370c3998141ab8c8b7"
uuid = "0bc81568-2411-4001-9bf1-c899fa54f385"
version = "0.3.3"

[[HTTP]]
deps = ["Base64", "Dates", "IniFile", "MbedTLS", "Sockets"]
git-tree-sha1 = "c7ec02c4c6a039a98a15f955462cd7aea5df4508"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.8.19"

[[HarfBuzz_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Gettext_jll", "Glib_jll", "Graphite2_jll", "ICU_jll", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "30237d3202f1d4ad9eda0a53b4272078effc50cd"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.6.1+9"

[[Hexagons]]
deps = ["Test"]
git-tree-sha1 = "de4a6f9e7c4710ced6838ca906f81905f7385fd6"
uuid = "a1b4810d-1bce-5fbd-ac56-80944d57a21f"
version = "0.2.0"

[[Highlights]]
deps = ["DocStringExtensions", "InteractiveUtils", "REPL"]
git-tree-sha1 = "f823a2d04fb233d52812c8024a6d46d9581904a4"
uuid = "eafb193a-b7ab-5a9e-9068-77385905fa72"
version = "0.4.5"

[[ICU_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b8de23644ee96884110e8071deed3ff0d2de4d9d"
uuid = "a51ab1cf-af8e-5615-a023-bc2c838bba6b"
version = "67.1.0+1"

[[IRTools]]
deps = ["InteractiveUtils", "MacroTools", "Test"]
git-tree-sha1 = "a8d88c05a23b44b4da6cf4fb5659e13ff95e0f47"
uuid = "7869d1d1-7146-5819-86e3-90919afe41df"
version = "0.4.1"

[[IdentityRanges]]
deps = ["OffsetArrays"]
git-tree-sha1 = "be8fcd695c4da16a1d6d0cd213cb88090a150e3b"
uuid = "bbac6d45-d8f3-5730-bfe4-7a449cd117ca"
version = "0.3.1"

[[IfElse]]
git-tree-sha1 = "28e837ff3e7a6c3cdb252ce49fb412c8eb3caeef"
uuid = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
version = "0.1.0"

[[ImageAxes]]
deps = ["AxisArrays", "ImageCore", "Reexport", "SimpleTraits"]
git-tree-sha1 = "5534929efb43df695d560f0e29fcdb4caf2f75e7"
uuid = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
version = "0.6.7"

[[ImageContrastAdjustment]]
deps = ["ColorVectorSpace", "ImageCore", "ImageTransformations", "MappedArrays", "Parameters"]
git-tree-sha1 = "d22d89e03c8f617e0ae31886ca60e291b548cf59"
uuid = "f332f351-ec65-5f6a-b3d1-319c6670881a"
version = "0.3.5"

[[ImageCore]]
deps = ["Colors", "FixedPointNumbers", "Graphics", "MappedArrays", "MosaicViews", "OffsetArrays", "PaddedViews", "Reexport", "Requires"]
git-tree-sha1 = "b6d3bc61ad9509332317c280b4b271f7d3a3b5ae"
uuid = "a09fc81d-aa75-5fe9-8630-4744c3626534"
version = "0.8.18"

[[ImageDistances]]
deps = ["ColorVectorSpace", "Distances", "ImageCore", "LinearAlgebra", "MappedArrays", "Statistics"]
git-tree-sha1 = "39e886e1f0de28d40d3ca08a8febf0c03aeffb0d"
uuid = "51556ac3-7006-55f5-8cb3-34580c88182d"
version = "0.2.8"

[[ImageFiltering]]
deps = ["CatIndices", "ColorVectorSpace", "ComputationalResources", "DataStructures", "FFTViews", "FFTW", "ImageCore", "ImageMetadata", "LinearAlgebra", "MappedArrays", "OffsetArrays", "Requires", "SparseArrays", "StaticArrays", "Statistics", "TiledIteration"]
git-tree-sha1 = "b6742d809aa16c3961034868b04fc162f3f01234"
uuid = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
version = "0.6.16"

[[ImageIO]]
deps = ["FileIO", "PNGFiles"]
git-tree-sha1 = "c4ac89fbc5e653ca2f6863df774247305bdadcc0"
uuid = "82e4d734-157c-48bb-816b-45c225c6df19"
version = "0.3.0"

[[ImageMetadata]]
deps = ["AxisArrays", "ColorVectorSpace", "ImageAxes", "ImageCore", "IndirectArrays"]
git-tree-sha1 = "ff77c7f234e7d8a618958fcf23b6959f2cbef2c6"
uuid = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
version = "0.9.4"

[[ImageMorphology]]
deps = ["ColorVectorSpace", "ImageCore", "LinearAlgebra", "TiledIteration"]
git-tree-sha1 = "113df7743f1e18da5f5ea5f98eb59ceb77092734"
uuid = "787d08f9-d448-5407-9aad-5290dd7ab264"
version = "0.2.9"

[[ImageQualityIndexes]]
deps = ["ColorVectorSpace", "ImageCore", "ImageDistances", "ImageFiltering", "MappedArrays", "OffsetArrays", "Statistics"]
git-tree-sha1 = "7811be6a6df3414f167ba597634acbf986dca1b6"
uuid = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
version = "0.2.0"

[[ImageShow]]
deps = ["Base64", "FileIO", "ImageCore", "Requires"]
git-tree-sha1 = "c9df184bc7c2e665f971079174aabb7d18f1845f"
uuid = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
version = "0.2.3"

[[ImageTransformations]]
deps = ["AxisAlgorithms", "ColorVectorSpace", "CoordinateTransformations", "IdentityRanges", "ImageCore", "Interpolations", "OffsetArrays", "Rotations", "StaticArrays"]
git-tree-sha1 = "5a0207dafba64650268bb5718875c0eea441e1ee"
uuid = "02fcd773-0e25-5acc-982a-7f6622650795"
version = "0.8.6"

[[Images]]
deps = ["AxisArrays", "Base64", "ColorVectorSpace", "FileIO", "Graphics", "ImageAxes", "ImageContrastAdjustment", "ImageCore", "ImageDistances", "ImageFiltering", "ImageMetadata", "ImageMorphology", "ImageQualityIndexes", "ImageShow", "ImageTransformations", "IndirectArrays", "OffsetArrays", "Random", "Reexport", "SparseArrays", "StaticArrays", "Statistics", "StatsBase", "TiledIteration"]
git-tree-sha1 = "46ded76802845f054e521819e0ba5a962b0d5887"
uuid = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
version = "0.23.0"

[[IndirectArrays]]
git-tree-sha1 = "c2a145a145dc03a7620af1444e0264ef907bd44f"
uuid = "9b13fd28-a010-5f03-acff-a1bbcff69959"
version = "0.5.1"

[[InfiniteArrays]]
deps = ["DSP", "FillArrays", "LazyArrays", "LinearAlgebra", "Statistics"]
git-tree-sha1 = "aa50bca542c26505efb399290eb5f83e995517bc"
uuid = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
version = "0.8.2"

[[Inflate]]
git-tree-sha1 = "f5fc07d4e706b84f72d54eedcc1c13d92fb0871c"
uuid = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
version = "0.1.2"

[[IniFile]]
deps = ["Test"]
git-tree-sha1 = "098e4d2c533924c921f9f9847274f2ad89e018b8"
uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
version = "0.5.0"

[[IntelOpenMP_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fb8e1c7a5594ba56f9011310790e03b5384998d6"
uuid = "1d5cc7b8-4909-519e-a0f8-d0f5ad9712d0"
version = "2018.0.3+0"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "LinearAlgebra", "OffsetArrays", "Random", "Ratios", "SharedArrays", "SparseArrays", "StaticArrays", "WoodburyMatrices"]
git-tree-sha1 = "2b7d4e9be8b74f03115e64cf36ed2f48ae83d946"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.12.10"

[[IntervalArithmetic]]
deps = ["CRlibm", "FastRounding", "LinearAlgebra", "Markdown", "Random", "RecipesBase", "RoundingEmulator", "SetRounding", "StaticArrays"]
git-tree-sha1 = "e12dc113568462326f0c3122faf35f019fff0543"
uuid = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
version = "0.17.5"

[[IntervalSets]]
deps = ["Dates", "EllipsisNotation", "Statistics"]
git-tree-sha1 = "3b1cef135bc532b3c3401b309e1b8a2a2ba26af5"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.5.1"

[[Intervals]]
deps = ["Dates", "Printf", "RecipesBase", "Serialization", "TimeZones"]
git-tree-sha1 = "9da845579d1dce4ce5118008c3fe6df17260bb46"
uuid = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
version = "1.4.2"

[[InvertedIndices]]
deps = ["Test"]
git-tree-sha1 = "15732c475062348b0165684ffe28e85ea8396afc"
uuid = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
version = "1.0.0"

[[IterTools]]
git-tree-sha1 = "05110a2ab1fc5f932622ffea2a003221f4782c18"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.3.0"

[[IterativeSolvers]]
deps = ["LinearAlgebra", "Printf", "Random", "RecipesBase", "SparseArrays"]
git-tree-sha1 = "3b7e2aac8c94444947facea7cc7ca91c49169be0"
uuid = "42fd0dbc-a981-5370-80f2-aaf504508153"
version = "0.8.4"

[[IteratorInterfaceExtensions]]
git-tree-sha1 = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "1.0.0"

[[JLLWrappers]]
git-tree-sha1 = "dbc0967f6403829a6682493fdb4ec7c0ebfd2e68"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.1.1"

[[JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.1"

[[JSON2]]
deps = ["Dates", "Parsers", "Test"]
git-tree-sha1 = "66397cc6c08922f98a28ab05a8d3002f9853b129"
uuid = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
version = "0.3.2"

[[JSONSchema]]
deps = ["HTTP", "JSON", "ZipFile"]
git-tree-sha1 = "a9ecdbc90be216912a2e3e8a8e38dc4c93f0d065"
uuid = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
version = "0.3.2"

[[JuMP]]
deps = ["Calculus", "DataStructures", "ForwardDiff", "JSON", "LinearAlgebra", "MathOptInterface", "MutableArithmetics", "NaNMath", "Random", "SparseArrays", "Statistics"]
git-tree-sha1 = "766014f271bd33b7f9d9bdc4847e214ee20ae84d"
uuid = "4076af6c-e467-56ae-b986-b466b2749572"
version = "0.21.4"

[[JuliaInterpreter]]
deps = ["CodeTracking", "InteractiveUtils", "Random", "UUIDs"]
git-tree-sha1 = "5b9b328eeea7bb85caca1576c15041e8faeb9041"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.8.1"

[[JuliaVariables]]
deps = ["MLStyle", "NameResolution"]
git-tree-sha1 = "e0fcfa0a2f6122fbe13603764c5310dde00c5593"
uuid = "b14d175d-62b4-44ba-8fb7-3064adc8c3ec"
version = "0.2.3"

[[Juno]]
deps = ["Base64", "Logging", "Media", "Profile"]
git-tree-sha1 = "07cb43290a840908a771552911a6274bc6c072c7"
uuid = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
version = "0.8.4"

[[KernelDensity]]
deps = ["Distributions", "DocStringExtensions", "FFTW", "Interpolations", "StatsBase"]
git-tree-sha1 = "2fdea3992af1bd7a90535d2937555d7b69d5e5ee"
uuid = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
version = "0.6.1"

[[LAME_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "df381151e871f41ee86cee4f5f6fd598b8a68826"
uuid = "c1c5ebd0-6772-5130-a774-d5fcae4a789d"
version = "3.100.0+3"

[[LLVM]]
deps = ["CEnum", "Libdl", "Printf", "Unicode"]
git-tree-sha1 = "a662366a5d485dee882077e8da3e1a95a86d097f"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "2.0.0"

[[LZO_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9d0c44be3e6d9690b19fa2cddb4c2e4b267ef425"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.0+2"

[[LaTeXStrings]]
git-tree-sha1 = "c7aebfecb1a60d59c0fe023a68ec947a208b1e6b"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.2.0"

[[LabelledArrays]]
deps = ["ArrayInterface", "LinearAlgebra", "MacroTools", "StaticArrays"]
git-tree-sha1 = "5e04374019448f8509349948ab504f117e3b575a"
uuid = "2ee39098-c373-598a-b85f-a56591580800"
version = "1.3.0"

[[Latexify]]
deps = ["Formatting", "InteractiveUtils", "LaTeXStrings", "MacroTools", "Markdown", "Printf", "Requires"]
git-tree-sha1 = "829b033e31573b8ffdd14e0d47154fd3ddc7abbf"
uuid = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
version = "0.14.0"

[[LazyArrays]]
deps = ["ArrayLayouts", "FillArrays", "LinearAlgebra", "MacroTools", "MatrixFactorizations", "SparseArrays", "StaticArrays"]
git-tree-sha1 = "1e9f6f50e6b39b2cabb18d5f0fafdd45d9c2a28f"
uuid = "5078a376-72f3-5289-bfd5-ec5146d43c02"
version = "0.18.1"

[[LazySets]]
deps = ["Distributed", "GLPK", "GLPKMathProgInterface", "InteractiveUtils", "IntervalArithmetic", "JuMP", "LinearAlgebra", "MathProgBase", "Random", "RecipesBase", "Reexport", "Requires", "SharedArrays", "SparseArrays"]
git-tree-sha1 = "27ebe06bd55e6170805a7154b9efe9c48a17156b"
uuid = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
version = "1.37.10"

[[LeftChildRightSiblingTrees]]
deps = ["AbstractTrees"]
git-tree-sha1 = "71be1eb5ad19cb4f61fa8c73395c0338fd092ae0"
uuid = "1d6d02ad-be62-4b6b-8a6d-2f90e265016e"
version = "0.1.2"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[LibVPX_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "85fcc80c3052be96619affa2fe2e6d2da3908e11"
uuid = "dd192d2f-8180-539f-9fb4-cc70b1dcf69a"
version = "1.9.0+1"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libffi_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "a30d50f837074b6ab43b81d9dd8be190b40cdd45"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.1+3"

[[Libgcrypt_jll]]
deps = ["Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "6b68e8b88e5eee917427a09d7bf15bd838576ba3"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.5+3"

[[Libglvnd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_libXext_jll"]
git-tree-sha1 = "5b1a5ff82d8a17e119369a004f60b2ac81a79b64"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.3.0+2"

[[Libgpg_error_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "83b5c9df3a53a570c8fc2a0d7643a2e30a6a141c"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.36.0+2"

[[Libiconv_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7c36dfe7971e55da03d8f54b67d4b3fb8ee01d63"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.0+6"

[[Libmount_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "ac69889ea9ee389e8bacab1bedc605c25d1ca960"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.34.0+2"

[[Libuuid_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "90bf54060f5223bf7ac450bb9c56d1334d31d04e"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.34.0+6"

[[LightGraphs]]
deps = ["ArnoldiMethod", "DataStructures", "Distributed", "Inflate", "LinearAlgebra", "Random", "SharedArrays", "SimpleTraits", "SparseArrays", "Statistics"]
git-tree-sha1 = "6f85a35d2377cb2db1bc448ed0d6340d2bb1ea64"
uuid = "093fc24a-ae57-5d10-9952-331d41423f4d"
version = "1.3.3"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Literate]]
deps = ["Base64", "JSON", "REPL"]
git-tree-sha1 = "7f289e9db7a93d30b9a44af4a8ae9cf92af74683"
uuid = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
version = "2.7.0"

[[LiveServer]]
deps = ["Crayons", "FileWatching", "HTTP", "Pkg", "Sockets", "Test"]
git-tree-sha1 = "41b8ef80352c22135016c3431518969101f359f3"
uuid = "16fef848-5104-11e9-1b77-fb7a48bbb589"
version = "0.5.7"

[[Loess]]
deps = ["Distances", "Random", "Statistics", "Test"]
git-tree-sha1 = "0ee46caf683a422b595be4dfaed6cda28f541e25"
uuid = "4345ca2d-374a-55d4-8d30-97f9976e7612"
version = "0.5.0"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[LoggingExtras]]
deps = ["Dates"]
git-tree-sha1 = "03289aba73c0abc25ff0229bed60f2a4129cd15c"
uuid = "e6f89c97-d47a-5376-807f-9c37f3926c36"
version = "0.4.2"

[[LoopVectorization]]
deps = ["DocStringExtensions", "LinearAlgebra", "OffsetArrays", "SIMDPirates", "SLEEFPirates", "UnPack", "VectorizationBase"]
git-tree-sha1 = "3242a8f411e19eda9adc49d0b877681975c11375"
uuid = "bdcacae8-1622-11e9-2a5c-532679323890"
version = "0.8.26"

[[LowRankApprox]]
deps = ["FFTW", "FillArrays", "LinearAlgebra", "Nullables", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "945c7da49e1c999956b21b106b238f9bd7ab1a63"
uuid = "898213cb-b102-5a47-900c-97e73b919f73"
version = "0.4.1"

[[LoweredCodeUtils]]
deps = ["JuliaInterpreter"]
git-tree-sha1 = "00c64cd799a9450e4d1efe8ad6549de72702f7fe"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
version = "1.2.3"

[[MD5]]
deps = ["Random", "SHA"]
git-tree-sha1 = "eeffe42284464c35a08026d23aa948421acf8923"
uuid = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
version = "0.2.1"

[[MKL_jll]]
deps = ["IntelOpenMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "eb540ede3aabb8284cb482aa41d00d6ca850b1f8"
uuid = "856f044c-d86e-5d09-b602-aeab76dc8ba7"
version = "2020.2.254+0"

[[MLStyle]]
git-tree-sha1 = "937eda9ce36fcce082a42edd7181c8d23f4eb550"
uuid = "d8e11817-5142-5d16-987a-aa16d5891078"
version = "0.4.6"

[[MPFR_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "301ce96952df90bbaa2c66112b7c1f15ced2b55b"
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"
version = "4.1.0+1"

[[MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "f7d2e3f654af75f01ec49be82c231c382214223a"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.5"

[[MappedArrays]]
git-tree-sha1 = "e2a02fe7ee86a10c707ff1756ab1650b40b140bb"
uuid = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
version = "0.2.2"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Match]]
git-tree-sha1 = "5cf525d97caf86d29307150fcba763a64eaa9cbe"
uuid = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
version = "1.1.0"

[[MathOptInterface]]
deps = ["BenchmarkTools", "CodecBzip2", "CodecZlib", "JSON", "JSONSchema", "LinearAlgebra", "MutableArithmetics", "OrderedCollections", "SparseArrays", "Test", "Unicode"]
git-tree-sha1 = "5a1d631e0a9087d425e024d66b9c71e92e78fda8"
uuid = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
version = "0.9.17"

[[MathProgBase]]
deps = ["LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "9abbe463a1e9fc507f12a69e7f29346c2cdc472c"
uuid = "fdba3010-5040-5b88-9595-932c9decdf73"
version = "0.7.8"

[[MatrixFactorizations]]
deps = ["ArrayLayouts", "LinearAlgebra", "Random"]
git-tree-sha1 = "cf040e1d053a83cde01ea964232e0c35a3dbed54"
uuid = "a3b82374-2e81-5b9e-98ce-41277c0e4c87"
version = "0.6.0"

[[MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "Random", "Sockets"]
git-tree-sha1 = "426a6978b03a97ceb7ead77775a1da066343ec6e"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.0.2"

[[MbedTLS_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "c0b1286883cac4e2b617539de41111e0776d02e8"
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
version = "2.16.8+0"

[[Measures]]
git-tree-sha1 = "e498ddeee6f9fdb4551ce855a46f54dbd900245f"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.3.1"

[[Media]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "75a54abd10709c01f1b86b84ec225d26e840ed58"
uuid = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27"
version = "0.5.0"

[[MeshIO]]
deps = ["ColorTypes", "FileIO", "GeometryBasics", "Printf"]
git-tree-sha1 = "287b3361bfb3edd3f84fd26760db0ea637a3907a"
uuid = "7269a6da-0436-5bbc-96c2-40638cbb6118"
version = "0.4.3"

[[MiniFB]]
deps = ["CEnum", "Colors", "MiniFB_jll"]
git-tree-sha1 = "4e93c94f369e6b3d3cda89507af850ffe5d9c947"
uuid = "cc649173-1898-4bb8-8a16-ca5f88bd87d9"
version = "0.1.1"

[[MiniFB_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "5f4d80ac70393d7a77a82ba916ef08fed271e44a"
uuid = "b93afbca-07d8-5443-9979-bb4221978155"
version = "0.1.1+1"

[[Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "ed61674a0864832495ffe0a7e889c0da76b0f4c8"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.4.4"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Mocking]]
deps = ["ExprTools"]
git-tree-sha1 = "916b850daad0d46b8c71f65f719c49957e9513ed"
uuid = "78c3b35d-d492-501b-9361-3d52fe80e533"
version = "0.7.1"

[[ModelingToolkit]]
deps = ["ArrayInterface", "DataStructures", "DiffEqBase", "DiffEqJump", "DiffRules", "Distributed", "DocStringExtensions", "GeneralizedGenerated", "IfElse", "LabelledArrays", "Latexify", "Libdl", "LightGraphs", "LinearAlgebra", "MacroTools", "NaNMath", "RecursiveArrayTools", "Requires", "SafeTestsets", "SparseArrays", "SpecialFunctions", "StaticArrays", "SymbolicUtils", "TreeViews", "UnPack", "Unitful"]
git-tree-sha1 = "a2777851fd21be36882ddafe5b5e2036cdc14636"
uuid = "961ee093-0014-501f-94e3-6117800e7a78"
version = "3.20.1"

[[ModernGL]]
deps = ["Libdl"]
git-tree-sha1 = "326957556e9cc9253615114c04bb0096a2a69bb8"
uuid = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
version = "1.1.2"

[[MosaicViews]]
deps = ["MappedArrays", "OffsetArrays", "PaddedViews"]
git-tree-sha1 = "29d121f9e7a6cf081278029121ed90e1f3b33de8"
uuid = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
version = "0.2.3"

[[MuladdMacro]]
git-tree-sha1 = "c6190f9a7fc5d9d5915ab29f2134421b12d24a68"
uuid = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
version = "0.2.2"

[[MutableArithmetics]]
deps = ["LinearAlgebra", "SparseArrays", "Test"]
git-tree-sha1 = "6cf09794783b9de2e662c4e8b60d743021e338d0"
uuid = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
version = "0.2.10"

[[NNlib]]
deps = ["Libdl", "LinearAlgebra", "Pkg", "Requires", "Statistics"]
git-tree-sha1 = "1ef04283efe283be08e2d0de842f5e5286dd0b7a"
uuid = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
version = "0.7.5"

[[NaNMath]]
git-tree-sha1 = "c84c576296d0e2fbb3fc134d3e09086b3ea617cd"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.4"

[[NameResolution]]
deps = ["PrettyPrint"]
git-tree-sha1 = "1a0fa0e9613f46c9b8c11eee38ebb4f590013c5e"
uuid = "71a1bf82-56d0-4bbc-8a3c-48b961074391"
version = "0.1.5"

[[NamedDims]]
deps = ["LinearAlgebra", "Pkg", "Requires", "Statistics"]
git-tree-sha1 = "263f7305bfa5b8b69cd3239ec6a4c037ff96b3df"
uuid = "356022a1-0364-5f58-8944-0da4b18d706f"
version = "0.2.28"

[[NodeJS]]
deps = ["Pkg"]
git-tree-sha1 = "350ac618f41958e6e0f6b0d2005ae4547eb1b503"
uuid = "2bd173c7-0d6d-553b-b6af-13a54713934c"
version = "1.1.1"

[[Nullables]]
git-tree-sha1 = "8f87854cc8f3685a60689d8edecaa29d2251979b"
uuid = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
version = "1.0.0"

[[Observables]]
git-tree-sha1 = "635fe10760447cfa86f5118edf2f47eb864fb495"
uuid = "510215fc-4207-5dde-b226-833fc4488ee2"
version = "0.3.2"

[[OffsetArrays]]
git-tree-sha1 = "a416e2f267e2c8729f25bcaf1ce19d2893faf393"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "1.3.1"

[[Ogg_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "a42c0f138b9ebe8b58eba2271c5053773bde52d0"
uuid = "e7412a2a-1a6e-54c0-be00-318e2571c051"
version = "1.3.4+2"

[[OpenBLAS_jll]]
deps = ["CompilerSupportLibraries_jll", "Libdl", "Pkg"]
git-tree-sha1 = "5fae4d1510bdcf7768cc951878b8aa48666c58a8"
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"
version = "0.3.10+0"

[[OpenSSL_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "71bbbc616a1d710879f5a1021bcba65ffba6ce58"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.1+6"

[[OpenSpecFun_jll]]
deps = ["CompilerSupportLibraries_jll", "Libdl", "Pkg"]
git-tree-sha1 = "d51c416559217d974a1113522d5919235ae67a87"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.3+3"

[[Opus_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "f9d57f4126c39565e05a2b0264df99f497fc6f37"
uuid = "91d4177d-7536-5919-b921-800302f37372"
version = "1.3.1+3"

[[OrderedCollections]]
git-tree-sha1 = "16c08bf5dba06609fe45e30860092d6fa41fde7b"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.3.1"

[[PCRE_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9f6be70c2b80ca004d18a4a38f5724264b4115c0"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.42.0+3"

[[PDMats]]
deps = ["LinearAlgebra", "SparseArrays", "SuiteSparse", "Test"]
git-tree-sha1 = "95a4038d1011dfdbde7cecd2ad0ac411e53ab1bc"
uuid = "90014a1f-27ba-587c-ab20-58faa44d9150"
version = "0.10.1"

[[PNGFiles]]
deps = ["CEnum", "ImageCore", "IndirectArrays", "OffsetArrays", "libpng_jll"]
git-tree-sha1 = "2252a42725b28193740fdbed5d85578ac642a074"
uuid = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
version = "0.3.1"

[[Packing]]
deps = ["GeometryBasics"]
git-tree-sha1 = "f4049d379326c2c7aa875c702ad19346ecb2b004"
uuid = "19eb6ba3-879d-56ad-ad62-d5c202156566"
version = "0.4.1"

[[PaddedViews]]
deps = ["OffsetArrays"]
git-tree-sha1 = "24f4e937212b79ced6bcba6c4788407081ed68f0"
uuid = "5432bcbf-9aad-5242-b902-cca2824c8663"
version = "0.5.6"

[[Pango_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "HarfBuzz_jll", "Libdl", "Pkg"]
git-tree-sha1 = "37918672870fbd48c3da80a19b125782759bede7"
uuid = "36c8627f-9965-5494-a995-c6b170f724f3"
version = "1.42.4+9"

[[Parameters]]
deps = ["OrderedCollections", "UnPack"]
git-tree-sha1 = "38b2e970043613c187bd56a995fe2e551821eb4a"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.12.1"

[[Parsers]]
deps = ["Dates"]
git-tree-sha1 = "6fa4202675c05ba0f8268a6ddf07606350eda3ce"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "1.0.11"

[[Pixman_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "f3515e3d8f4b0fd4df9465d9a79cb478dcd84242"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.38.4+4"

[[Pkg]]
deps = ["Artifacts", "Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "TOML", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PlotThemes]]
deps = ["PlotUtils", "Requires", "Statistics"]
git-tree-sha1 = "c6f5ea535551b3b16835134697f0c65d06c94b91"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "2.0.0"

[[PlotUtils]]
deps = ["ColorSchemes", "Colors", "Dates", "Printf", "Random", "Reexport", "Statistics"]
git-tree-sha1 = "4e098f88dad9a2b518b83124a116be1c49e2b2bf"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "1.0.7"

[[PlotlyBase]]
deps = ["Base64", "Dates", "DelimitedFiles", "DocStringExtensions", "JSON", "LaTeXStrings", "Logging", "Pkg", "Requires", "Statistics", "UUIDs"]
git-tree-sha1 = "b33809ab5a35bf41d1fd7c851b52e32004392933"
uuid = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
version = "0.4.1"

[[Plots]]
deps = ["Base64", "Contour", "Dates", "FFMPEG", "FixedPointNumbers", "GR", "GeometryBasics", "GeometryTypes", "JSON", "Latexify", "LinearAlgebra", "Measures", "NaNMath", "Pkg", "PlotThemes", "PlotUtils", "Printf", "REPL", "Random", "RecipesBase", "RecipesPipeline", "Reexport", "Requires", "Showoff", "SparseArrays", "Statistics", "StatsBase", "UUIDs"]
git-tree-sha1 = "9376c978098b85a001870ad0270569b6e445f154"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "1.6.10"

[[PoissonRandom]]
deps = ["Random", "Statistics", "Test"]
git-tree-sha1 = "44d018211a56626288b5d3f8c6497d28c26dc850"
uuid = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
version = "0.4.0"

[[Polynomials]]
deps = ["Intervals", "LinearAlgebra", "OffsetArrays", "RecipesBase"]
git-tree-sha1 = "ce5fe493693b1ca81aa70b806e353a288f73ec7f"
uuid = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
version = "1.1.9"

[[PooledArrays]]
deps = ["DataAPI"]
git-tree-sha1 = "b1333d4eced1826e15adbdf01a4ecaccca9d353c"
uuid = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
version = "0.5.3"

[[PrettyPrint]]
git-tree-sha1 = "632eb4abab3449ab30c5e1afaa874f0b98b586e4"
uuid = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"
version = "0.2.0"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[ProgressLogging]]
deps = ["Logging", "SHA", "UUIDs"]
git-tree-sha1 = "59398022b661b6fd569f25de6b18fde39843196a"
uuid = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
version = "0.1.3"

[[ProgressMeter]]
deps = ["Distributed", "Printf"]
git-tree-sha1 = "4cff8da83f89e06eeae5b81307a08bb33a96a602"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "1.4.0"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra"]
git-tree-sha1 = "12fbe86da16df6679be7521dfb39fbc861e1dc7b"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.4.1"

[[RData]]
deps = ["CategoricalArrays", "CodecZlib", "DataFrames", "Dates", "FileIO", "Requires", "TimeZones", "Unicode"]
git-tree-sha1 = "10693c581956334a368c26b7c544e406c4c94385"
uuid = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
version = "0.7.2"

[[RDatasets]]
deps = ["CSV", "CodecZlib", "DataFrames", "FileIO", "Printf", "RData", "Reexport"]
git-tree-sha1 = "68e425aa9461f45e286553cc4d049c0710dcc3aa"
uuid = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
version = "0.6.10"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RandomNumbers]]
deps = ["Random", "Requires"]
git-tree-sha1 = "441e6fc35597524ada7f85e13df1f4e10137d16f"
uuid = "e6cf234a-135c-5ec9-84dd-332b85af5143"
version = "1.4.0"

[[RangeArrays]]
git-tree-sha1 = "b9039e93773ddcfc828f12aadf7115b4b4d225f5"
uuid = "b3c3ace0-ae52-54e7-9d0b-2c1406fd6b9d"
version = "0.3.2"

[[Ratios]]
git-tree-sha1 = "37d210f612d70f3f7d57d488cb3b6eff56ad4e41"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.4.0"

[[RecipesBase]]
git-tree-sha1 = "6ee6c35fe69e79e17c455a386c1ccdc66d9f7da4"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.1.0"

[[RecipesPipeline]]
deps = ["Dates", "NaNMath", "PlotUtils", "RecipesBase"]
git-tree-sha1 = "4a325c9bcc2d8e62a8f975b9666d0251d53b63b9"
uuid = "01d81517-befc-4cb6-b9ec-a95719d0359c"
version = "0.1.13"

[[RecursiveArrayTools]]
deps = ["ArrayInterface", "LinearAlgebra", "RecipesBase", "Requires", "StaticArrays", "Statistics", "ZygoteRules"]
git-tree-sha1 = "639b3c4c7bcdc42be3ce69c4919eac17be73242b"
uuid = "731186ca-8d62-57ce-b412-fbd966d074cd"
version = "2.7.2"

[[RecursiveFactorization]]
deps = ["LinearAlgebra", "LoopVectorization", "VectorizationBase"]
git-tree-sha1 = "4ca0bdad1d69abbd59c35af89a9a2ab6cd5ef0f1"
uuid = "f2c3362d-daeb-58d1-803e-2bc74f2840b4"
version = "0.1.4"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "2fc2e1ab606a5dca7bbad9036a694553c3a57926"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.0.3"

[[Revise]]
deps = ["CodeTracking", "Distributed", "FileWatching", "JuliaInterpreter", "LibGit2", "LoweredCodeUtils", "OrderedCollections", "Pkg", "REPL", "Requires", "UUIDs", "Unicode"]
git-tree-sha1 = "f0ba1f1f62dccae6e69f2ff99cba667ff1f0a410"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "3.1.5"

[[Rmath]]
deps = ["Random", "Rmath_jll"]
git-tree-sha1 = "86c5647b565873641538d8f812c04e4c9dbeb370"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.6.1"

[[Rmath_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "d76185aa1f421306dec73c057aa384bad74188f0"
uuid = "f50d1b31-88e8-58de-be2c-1cc44531875f"
version = "0.2.2+1"

[[Roots]]
deps = ["Printf"]
git-tree-sha1 = "1211c7c1928c1ed29cdcef65979b7a791e3b9fbe"
uuid = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
version = "1.0.5"

[[Rotations]]
deps = ["LinearAlgebra", "StaticArrays", "Statistics"]
git-tree-sha1 = "445b72242dbdecba9bfc42034daafdd901bbf6a9"
uuid = "6038ab10-8711-5258-84ad-4b1120ba62dc"
version = "1.0.1"

[[RoundingEmulator]]
git-tree-sha1 = "40b9edad2e5287e05bd413a38f61a8ff55b9557b"
uuid = "5eaf0fd0-dfba-4ccb-bf02-d820a40db705"
version = "0.2.1"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[SIMDPirates]]
deps = ["VectorizationBase"]
git-tree-sha1 = "450d163d3279a1d35e3aad3352a5167ef21b84a4"
uuid = "21efa798-c60a-11e8-04d3-e1a92915a26a"
version = "0.8.25"

[[SLEEFPirates]]
deps = ["Libdl", "SIMDPirates", "VectorizationBase"]
git-tree-sha1 = "67ae90a18aa8c22bf159318300e765fbd89ddf6e"
uuid = "476501e8-09a2-5ece-8869-fb82de89a1fa"
version = "0.5.5"

[[SafeTestsets]]
deps = ["Test"]
git-tree-sha1 = "36ebc5622c82eb9324005cc75e7e2cc51181d181"
uuid = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
version = "0.0.1"

[[SentinelArrays]]
deps = ["Dates", "Random"]
git-tree-sha1 = "6ccde405cf0759eba835eb613130723cb8f10ff9"
uuid = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
version = "1.2.16"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SetRounding]]
deps = ["Test"]
git-tree-sha1 = "faca28c7937138d560ede5bfef2076d0cdf3584b"
uuid = "3cc68bcd-71a2-5612-b932-767ffbe40ab0"
version = "0.2.0"

[[ShaderAbstractions]]
deps = ["ColorTypes", "FixedPointNumbers", "GeometryBasics", "LinearAlgebra", "Observables", "StaticArrays", "StructArrays", "Tables"]
git-tree-sha1 = "e57b742c93fd6044a42a4a99751a60fe73985d8a"
uuid = "65257c39-d410-5151-9873-9b3e5be5013e"
version = "0.2.3"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[ShiftedArrays]]
git-tree-sha1 = "22395afdcf37d6709a5a0766cc4a5ca52cb85ea0"
uuid = "1277b4bf-5013-50f5-be3d-901d8477a67a"
version = "1.0.0"

[[Showoff]]
deps = ["Dates", "Grisu"]
git-tree-sha1 = "ee010d8f103468309b8afac4abb9be2e18ff1182"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "0.3.2"

[[SignedDistanceFields]]
deps = ["Random", "Statistics", "Test"]
git-tree-sha1 = "d263a08ec505853a5ff1c1ebde2070419e3f28e9"
uuid = "73760f76-fbc4-59ce-8f25-708e95d2df96"
version = "0.4.0"

[[SimpleTraits]]
deps = ["InteractiveUtils", "MacroTools"]
git-tree-sha1 = "daf7aec3fe3acb2131388f93a4c409b8c7f62226"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
version = "0.9.3"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "03f5898c9959f8115e30bc7226ada7d0df554ddd"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.1"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["OpenSpecFun_jll"]
git-tree-sha1 = "d8d8b8a9f4119829410ecd706da4cc8594a1e020"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.10.3"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "016d1e1a00fabc556473b07161da3d39726ded35"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.12.4"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics"]
git-tree-sha1 = "7bab7d4eb46b225b35179632852b595a3162cb61"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.33.2"

[[StatsFuns]]
deps = ["Rmath", "SpecialFunctions"]
git-tree-sha1 = "04a5a8e6ab87966b43f247920eab053fd5fdc925"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
version = "0.9.5"

[[StatsModels]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "Printf", "ShiftedArrays", "SparseArrays", "StatsBase", "StatsFuns", "Tables"]
git-tree-sha1 = "ada0ee19dd2927f92cfb8c73516ddc206afd34da"
uuid = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
version = "0.6.15"

[[StructArrays]]
deps = ["Adapt", "DataAPI", "Tables"]
git-tree-sha1 = "8099ed9fb90b6e754d6ba8c6ed8670f010eadca0"
uuid = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
version = "0.4.4"

[[StructTypes]]
deps = ["Dates", "UUIDs"]
git-tree-sha1 = "1ed04f622a39d2e5a6747c3a70be040c00333933"
uuid = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
version = "1.1.0"

[[SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "Serialization", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[SymbolicUtils]]
deps = ["AbstractAlgebra", "Combinatorics", "DataStructures", "NaNMath", "SpecialFunctions", "TimerOutputs"]
git-tree-sha1 = "3cd0b83054bd456ac5c8740900ef4d1f830462c0"
uuid = "d1185830-fcd6-423d-90d6-eec64667417b"
version = "0.5.1"

[[TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[[TableTraits]]
deps = ["IteratorInterfaceExtensions"]
git-tree-sha1 = "b1ad568ba658d8cbb3b892ed5380a6f3e781a81e"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "1.0.0"

[[Tables]]
deps = ["DataAPI", "DataValueInterfaces", "IteratorInterfaceExtensions", "LinearAlgebra", "TableTraits", "Test"]
git-tree-sha1 = "24a584cf65e2cfabdadc21694fb69d2e74c82b44"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
version = "1.1.0"

[[Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[[TerminalLoggers]]
deps = ["LeftChildRightSiblingTrees", "Logging", "Markdown", "Printf", "ProgressLogging", "UUIDs"]
git-tree-sha1 = "cbea752b5eef52a3e1188fb31580c3e4fa0cbc35"
uuid = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
version = "0.1.2"

[[Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[ThreadPools]]
deps = ["Printf", "RecipesBase", "Statistics"]
git-tree-sha1 = "4809b7746342115d4e20c4ccd1a34b52967cb43d"
uuid = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
version = "1.1.3"

[[TiledIteration]]
deps = ["OffsetArrays"]
git-tree-sha1 = "05f74c5b3c00d5336bc109416df2df907e3bd91d"
uuid = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"
version = "0.2.5"

[[TimeZones]]
deps = ["Dates", "EzXML", "Mocking", "Pkg", "Printf", "RecipesBase", "Serialization", "Unicode"]
git-tree-sha1 = "2c48caca8f3912857973590a9757e1f86cbbff81"
uuid = "f269a46b-ccf7-5d73-abea-4c690281aa53"
version = "1.4.0"

[[TimerOutputs]]
deps = ["Printf"]
git-tree-sha1 = "f458ca23ff80e46a630922c555d838303e4b9603"
uuid = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
version = "0.5.6"

[[ToeplitzMatrices]]
deps = ["AbstractFFTs", "FFTW", "LinearAlgebra", "StatsBase"]
git-tree-sha1 = "e318629aa5ff8894f63a198b22788253d67fe3b1"
uuid = "c751599d-da0a-543b-9d20-d0a503d91d24"
version = "0.6.2"

[[TranscodingStreams]]
deps = ["Random", "Test"]
git-tree-sha1 = "7c53c35547de1c5b9d46a4797cf6d8253807108c"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.9.5"

[[TreeViews]]
deps = ["Test"]
git-tree-sha1 = "8d0d7a3fe2f30d6a7f833a5f19f7c7a5b396eae6"
uuid = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"
version = "0.3.0"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[UnPack]]
git-tree-sha1 = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
version = "1.0.2"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[UnicodeFun]]
deps = ["REPL"]
git-tree-sha1 = "53915e50200959667e78a92a418594b428dffddf"
uuid = "1cfade01-22cf-5700-b092-accc4b62d6e1"
version = "0.4.1"

[[Unitful]]
deps = ["ConstructionBase", "LinearAlgebra", "Random"]
git-tree-sha1 = "ad27b1a82c81d2bb65fa3a94fa05b98136eefaad"
uuid = "1986cc42-f94f-5a68-af5c-568840ba703d"
version = "1.4.1"

[[VectorizationBase]]
deps = ["CpuId", "Libdl", "LinearAlgebra"]
git-tree-sha1 = "03e2fbb479a1ea350398195b6fbf439bae0f8260"
uuid = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
version = "0.12.33"

[[WithInclude]]
path = "../../../src/julia/WithInclude"
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758b0000"
version = "0.0.0+"

[[WoodburyMatrices]]
deps = ["LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "28ffe06d28b1ba8fdb2f36ec7bb079fac81bac0d"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.5.2"

[[XML2_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "ecff6bff03b35d482ad5eb51276d6fc4c823cd39"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.10+2"

[[XSLT_jll]]
deps = ["Libdl", "Libgcrypt_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "8bb981a5c4a7efc799250c46ef757cbfd6c5ba9b"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.33+3"

[[Xorg_libX11_jll]]
deps = ["Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "25ef1a3d04558407fc618797c1340d3703bacb94"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+3"

[[Xorg_libXau_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9284aed438cb747514ee02170f25c2f9cea91c00"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+3"

[[Xorg_libXcursor_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXfixes_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "f9e26bb7fe6e1cd7b5fb0ffa959fa3b263723f94"
uuid = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
version = "1.2.0+3"

[[Xorg_libXdmcp_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "95a233c8cf22e098be956a2fbed9db4ec02eadd0"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+3"

[[Xorg_libXext_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "d160f39dbee0faba7b65d62e8b3af4e508ec36b2"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+3"

[[Xorg_libXfixes_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "c090cd1180e6b1d67541f161bf1eb7a5530d7ba0"
uuid = "d091e8ba-531a-589c-9de9-94069b037ed8"
version = "5.0.3+3"

[[Xorg_libXi_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXfixes_jll"]
git-tree-sha1 = "33d931c90ea05cd9fdbbb40803070b404cc3d413"
uuid = "a51aa0fd-4e3c-5386-b890-e753decda492"
version = "1.7.10+3"

[[Xorg_libXinerama_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll"]
git-tree-sha1 = "df96a770b7e70ff0231ae0c28ef2bbdd24b6fbf3"
uuid = "d1454406-59df-5ea1-beac-c340f2130bc3"
version = "1.1.4+3"

[[Xorg_libXrandr_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "efac36579bc9241e831b43040df5d7cf723c4b97"
uuid = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
version = "1.5.2+3"

[[Xorg_libXrender_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "97a4104340d745968c78009854ab9369b59d7333"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+3"

[[Xorg_libpthread_stubs_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "20e2b3ee7eacf9f4f64e5804879b8b12eee436db"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+2"

[[Xorg_libxcb_jll]]
deps = ["Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "c1efb50fb6a8c40c45451611fbf93feabe5f9611"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+2"

[[Xorg_xtrans_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "52df68f05a75b81221a1d1420ce4a9c375b29ecc"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+2"

[[ZipFile]]
deps = ["Libdl", "Printf", "Zlib_jll"]
git-tree-sha1 = "c3a5637e27e914a7a445b8d0ad063d701931e9f7"
uuid = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
version = "0.9.3"

[[Zlib_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "ded43825988ace7a311ee7e1d0f09571822509c4"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+17"

[[Zygote]]
deps = ["AbstractFFTs", "ArrayLayouts", "ChainRules", "DiffRules", "Distributed", "FillArrays", "ForwardDiff", "Future", "IRTools", "InteractiveUtils", "LinearAlgebra", "LoopVectorization", "MacroTools", "NNlib", "NaNMath", "Random", "Requires", "SpecialFunctions", "Statistics", "ZygoteRules"]
git-tree-sha1 = "4eab8971579a9879ce260ac16a7c54935a79edb6"
uuid = "e88e6eb3-aa80-5325-afca-941959d7151f"
version = "0.5.8"

[[ZygoteRules]]
deps = ["MacroTools"]
git-tree-sha1 = "b3b4882cc9accf6731a08cc39543fbc6b669dca8"
uuid = "700de1a5-db45-46bc-99cf-38207098b444"
version = "0.2.0"

[[libass_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "acc685bcf777b2202a904cdcb49ad34c2fa1880c"
uuid = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0"
version = "0.14.0+4"

[[libfdk_aac_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "7a5780a0d9c6864184b3a2eeeb833a0c871f00ab"
uuid = "f638f0a6-7fb0-5443-88ba-1cc74229b280"
version = "0.1.6+4"

[[libpng_jll]]
deps = ["Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "0a93f3eae5b80f08dc789e549657c199f1da6417"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.37+5"

[[libvorbis_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ogg_jll", "Pkg"]
git-tree-sha1 = "fa14ac25af7a4b8a7f61b287a124df7aab601bcd"
uuid = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
version = "1.3.6+6"

[[x264_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "d713c1ce4deac133e3334ee12f4adff07f81778f"
uuid = "1270edf5-f2f9-52d2-97e9-ab00b5d0237a"
version = "2020.7.14+2"

[[x265_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "487da2f8f2f0c8ee0e83f39d13037d6bbf0a45ab"
uuid = "dfaa095f-4041-5dcd-9319-2fabd8486b76"
version = "3.0.0+3"
```

### PR DESCRIPTION
**Pull request by ianshmean**
Two things:
- This changes `Pkg.precompile()` to not throw. The error messages presented are high-level success or failure, hence I don't think they are informative enough to own the throw. The user or script should go-on to code loading and get the nicer stack trace.

@simonbyrne, it was mentioned by @KristofferC that you changed `precompile` to throw in the past. Is there a particular reason we should be aware of?

- Fixes an unintended auto precomp call during `Pkg.test` #2110 

Fixes #2110 
Fixes #2112 
Fixes #2118
Fixes #2116

### CODE REVIEW

**Comment by ianshmean** [comment]
I just added an immediate interrupt message to deter ctrl-c mashing and allow graceful exit

```
(@v1.6) pkg> precompile
Precompiling project...
  SentinelArrays ◓
  ProgressMeter ◓
  Xorg_xtrans_jll ◓
  FixedPointNumbers ◓
  Compat ◓
  Libuuid_jll ◓
  RangeArrays ✓
  Libgpg_error_jll ◓
  JLLWrappers ◓
  FileIO ◓
  OffsetArrays ✓
  hicolor_icon_theme_jll ✓
  Expat_jll ◓
  Glob ◓
  IterTools ◓
  Libiconv_jll ◓
^C Interrupted: Exiting precompilation...

```

**Comment by simonbyrne** [comment]
Precompilation errors were made fatal in #1940: the rationale was that if precompilation failed then the package was broken (either the package itself wouldn't load, or it should have precompilation disabled).

Why would you not want it to be an error?

**Comment by fredrikekre** [comment]
The previous implementation was only precompiling what would be loaded though and not everyhing in the manifest.

**Comment by simonbyrne** [comment]
I'm not opposed to that, I just want a precompilation failure to manifest as an error in the main process so that e.g. it can trigger a non-zero return code. The original (non fatal) behaviour was causing us significant problems for deployment.

**Comment by simonbyrne** [comment]
I think ideally you would want to catch the full stack trace of the error that caused the precompilation failure and print that. Unfortunately it seems that [`Base.compilecache` returns a generic error](https://github.com/JuliaLang/julia/blob/a1da84c3b0406e8378d8af781fe74ce749725d1f/base/loading.jl#L1360) because the compilation itself happens in a separate process.

**Comment by ianshmean** [comment]
Exactly. That's why this is tricky. We can't grab a meaningful error and show it later, it would have to be thrown instantly from the sub-process, and would mess up the parallel management.

How about if `Pkg.precompile()` and `pkg> precompile` throws, but auto-precompilation doesn't and just warns?
It sounds like in your case you're actively calling `Pkg.precompile()`, so that wouldn't change behavior, it just wouldn't be the full stack trace.

**Comment by simonbyrne** [comment]
That seems fine, but I don't see how it helps with giving meaningful feedback.

**Comment by KristofferC** [comment]
In that case, you would get the meaningful feedback when you activey try to use the package.

File: src/Operations.jl [hunk 1]
```diff
@@ -1565,7 +1565,7 @@ testfile(source_path::String) = joinpath(testdir(source_path), "runtests.jl")
 function test(ctx::Context, pkgs::Vector{PackageSpec};
               coverage=false, julia_args::Cmd=``, test_args::Cmd=``,
               test_fn=nothing)
-    Pkg.instantiate(ctx)
+    Pkg.instantiate(ctx; allow_autoprecomp = false)
```
Comment (fredrikekre) [inline src/Operations.jl:1568]: Why are we even instantiating here???

**Comment by ianshmean** [comment]
I figured out collecting errors, then at the end throwing and displaying all the internal stack traces of the failed direct deps. Requires https://github.com/JuliaLang/julia/pull/38017

CSV has an `error()` inserted. BinaryBuilderBase has a real error

Screen Shot 2020-10-13 at 4 17 52 PM

**Comment by ianshmean** [comment]
Added a fix for #2118. Packages that were printing to stdout during precomp were messing up the parallel printing

**Comment by ianshmean** [comment]
Added save/recall of the suspended package list via serialization, to a Pkg scratch space file named with the hash of the active project.
This allows the suspension of packages during auto-precomp to be specific to projects, and sustain through restarting julia

Fixes #2116

**Comment by ianshmean** [comment]
You can see this PR being temporarily used and passing CI over at https://github.com/JuliaLang/julia/pull/38017

**Comment by fredrikekre** [comment]
Would it be too crazy to have auto-precompilation fail silently and explicit calls to `Pkg.precompile()` throw?

**Comment by ianshmean** [comment]
That's what this PR does now

**Comment by fredrikekre** [comment]
Oh, ok.

File: src/Operations.jl [hunk 2]
```diff
@@ -14,12 +14,39 @@ import ..Artifacts: ensure_all_artifacts_installed, artifact_names, extract_all_
...
 # Utils #
 #########
 
+const PkgUUID = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
 const pkgs_precompile_suspended = Base.PkgId[]
+pkg_scratchpath() = joinpath(depots1(), "scratchspaces", PkgUUID)
+function save_suspended_packages()
+    path = pkg_scratchpath()
+    fpath = joinpath(path, string("suspend_cache_", hash(Base.active_project())))
+    try
```
Comment (KristofferC) [inline src/Operations.jl:29]: I think the try catch can be only around the `serialize`

**Comment by KristofferC** [comment]
> `ERROR: LoadError: LoadError: ArgumentError: Package Pkg does not have Serialization in its dependencies:`

Looks like the project file has to be updated.

**Comment by simonbyrne** [comment]
Nice!

File: src/Operations.jl (hunk 2 above)
Comment (ianshmean) [reply src/Operations.jl]: Yeah, thanks. I realised we don't need to try-catch the `serialize`, just the `deserialize`, and the file handling can be done via `isfile()`

**Comment by ianshmean** [comment]
https://github.com/JuliaLang/julia/pull/38017 is now merged. I'll wait for it to hit nightly and retrigger CI

**Comment by ianshmean** [comment]
Should be good to go now
