### PR TITLE
Replace UnstableIO with IOContext{IO}

### LINKED ISSUE #3722: missing API method closewrite for Pkg.UnstableIO
The UnstableIO type is missing the `closewrite` method which causes it to throw this error (which gets usually swallowed by precompile, but here I made it visible while checking for API mistakes)
```
    nested task error: MethodError: no method matching closewrite(::Pkg.UnstableIO)
    
    Closest candidates are:
      closewrite(!Matched::Base.BufferStream)
       @ Base stream.jl:1487
      closewrite(!Matched::Base.LibuvStream)
       @ Base stream.jl:437
      closewrite(!Matched::Base.GenericIOBuffer)
       @ Base iobuffer.jl:350
      ...
    
    Stacktrace:
     [1] (::Base.var"#848#849"{Pkg.UnstableIO, Bool, Base.PipeEndpoint, Pkg.UnstableIO, Base.PipeEndpoint})()
       @ Base ./process.jl:318
in expression starting at /home/vtjnash/julia/usr/share/julia/stdlib/v1.11/Pkg/src/precompile.jl:6
in expression starting at /home/vtjnash/julia/usr/share/julia/stdlib/v1.11/Pkg/src/Pkg.jl:3
in expression starting at stdin:3
```

### PR DESCRIPTION
**Pull request by mkitti**
While trying to send UnstableIO into Julia base, two suggestions arose:
1. Use `Base.inferencebarrier` to prevent specialization: 
   https://github.com/JuliaLang/julia/pull/52249#discussion_r1401199265
2. Use `IOContext{IO}` rather than introducing a new type:
   https://github.com/JuliaLang/julia/pull/52249#discussion_r1425332525

Fix #3722 (`IOContext` has `closewrite`)
Addresses part of #3702 by removing `UnstableIO` and its associated invalidations.

### CODE REVIEW

File: src/Pkg.jl [hunk 1]
```diff
@@ -41,14 +41,18 @@ const RESPECT_SYSIMAGE_VERSIONS = Ref(true)
...
-struct UnstableIO <: IO
-    io::IO
+# See discussion in https://github.com/JuliaLang/julia/pull/52249
+const UnstableIO = IOContext{IO}
+function unstableio(@nospecialize(io::IO))
+    # Needed to prevent specialization https://github.com/JuliaLang/julia/pull/52249#discussion_r1401199265
+    _io = Base.inferencebarrier(io)
+    IOContext{IO}(
+        _io,
+        get(_io,:color,false) ? Base.ImmutableDict{Symbol,Any}(:color, true) : Base.ImmutableDict{Symbol,Any}()
```
Comment (KristofferC) [inline src/Pkg.jl:51]: Why is this needed?

Comment (mkitti) [reply src/Pkg.jl:51]: Do you have another suggestion as how one might construct a `IOContext{IO}`?

```julia
julia> IOContext{IO}(stdout)
ERROR: MethodError: no method matching IOContext{IO}(::Base.TTY)

Closest candidates are:
  IOContext{IO_t}(::IO_t, ::Base.ImmutableDict{Symbol, Any}) where IO_t<:IO
   @ Base show.jl:291
```

File: src/Pkg.jl [hunk 2]
```diff
@@ -41,14 +41,18 @@ const RESPECT_SYSIMAGE_VERSIONS = Ref(true)
 # For globally overriding in e.g. tests
 const DEFAULT_IO = Ref{Union{IO,Nothing}}(nothing)
 
-struct UnstableIO <: IO
-    io::IO
+# See discussion in https://github.com/JuliaLang/julia/pull/52249
+const UnstableIO = IOContext{IO}
```
Comment (KristofferC) [inline src/Pkg.jl:45]: This can be removed I think? Or is it used somewhere else?

Comment (mkitti) [reply src/Pkg.jl:45]: There are a few other references to `UnstableIO` in Pkg.jl. I could get rid of the alias as its uses. Is that what you mean?

Comment (mkitti) [reply src/Pkg.jl]: I removed references to `UnstableIO` in 9d57162

File: src/Pkg.jl (hunk 1 above)
Comment (mkitti) [reply src/Pkg.jl:50]: An alternative is that I use `Base.unwrapcontext` instead of copying the code. I'm not sure if that complicates the inference barrier or not.

Comment (mkitti) [reply src/Pkg.jl:50]: This does cause compilation of `get` for the `IO` though.

**Comment by KristofferC** [comment]
Looks like this has to be rebased to update for another use of `UnstableIO` (looking at the CI):

```
┌ Pkg
│  WARNING: could not import Pkg.UnstableIO into Operations
└  
     Testing Running tests...
ERROR: LoadError: UndefVarError: `UnstableIO` not defined in `Pkg.Operations`
Stacktrace:
  [1] subprocess_handler(cmd::Cmd, io::IOContext{IO}, error_msg::String)
    @ Pkg.Operations ~/work/Pkg.jl/Pkg.jl/src/Operations.jl:2223
  [2] (::Pkg.Operations.var"#138#143"{Pkg.Types.Context})()
    @ Pkg.Operations ~/work/Pkg.jl/Pkg.jl/src/Operations.jl:2129
```

**Comment by KristofferC** [comment]
👍
