### PR TITLE
fix #1077: handle stdlibs in update_package_add and friends

### LINKED ISSUE #1077: Consecutive stdlib add's errors
```
(v1) pkg> add Test
 Resolving package versions...
  Updating `~/.julia/environments/v1/Project.toml`
  [8dfed614] + Test 
[...]

(v1) pkg> add Test
ERROR: MethodError: no method matching iterate(::Pkg.Types.VersionSpec)
```

### PR DESCRIPTION
**Pull request by fredrikekre**
Handle stdlibs explicitly in `update_package_add!`, `update_package_pin!`
and `update_package_test!`, since they are not versioned like other packages,
fixes #1077.

---
bors try

### CODE REVIEW

File: src/Operations.jl [hunk 1]
```diff
@@ -1033,10 +1034,12 @@ function update_package_pin!(pkg::PackageSpec, ::Nothing)
     if pkg.version == VersionSpec() # no version to pin
         pkgerror("Can not `pin` a package which does not exist in the manifest")
     end
+    is_stdlib(pkg.uuid) && pkgerror("cannot `pin` stdlibs.")
     pkg.pinned = true
 end
 
 function update_package_pin!(pkg::PackageSpec, entry::PackageEntry)
+    is_stdlib(pkg.uuid) && pkgerror("cannot `pin` stdlibs.")
```
Comment (fredrikekre) [inline src/Operations.jl]: Probably does not make sense to `pin` a stdlib. It is an error in 1.0 (`ERROR: KeyError: key "version" not found`) and 1.1 (`ERROR: MethodError: no method matching VersionNumber(::Nothing)`) so this is not a regression, and results in a better error message.

**Comment by fredrikekre** [comment]
bors try

File: src/Operations.jl [hunk 2]
```diff
@@ -900,8 +900,9 @@ function update_package_add(pkg::PackageSpec, entry::PackageEntry, is_dep::Bool)
     if entry.path !== nothing || entry.repo.url !== nothing || pkg.repo.url !== nothing
         return pkg # overwrite everything, nothing to copy over
     end
-    if is_dep && ((isa(pkg.version, VersionNumber) && entry.version == pkg.version) ||
-                 (!isa(pkg.version, VersionNumber) && entry.version ∈ pkg.version))
+    if is_dep && !is_stdlib(pkg.uuid) &&
```
Comment (00vareladavid) [inline src/Operations.jl]: I would prefer if the stdlib branch was separate. E.g. `is_stdlib(pkg.uuid) && return pkg`

Comment (00vareladavid) [reply src/Operations.jl]: Otherwise looks good

Comment (fredrikekre) [reply src/Operations.jl]: Yea, that is cleaner.
