### PR TITLE
REPL: Fix labels in env selection

### LINKED ISSUE #3031: Wrong labels in env selection
MWE:
```
julia> insert!(LOAD_PATH, 2, mktempdir())
julia> using PyPlot
 │ Package PyPlot not found, but a package named PyPlot is available from a registry. 
 │ Install package?
 │   (@v1.8) pkg> add PyPlot 
 └ Select environment:
 > 1: `/tmp/jl_5IzQiV` (@)
   2: `~/.julia/environments/v1.8/Project.toml` (/tmp/jl_5IzQiV)
```
The labels in brackets don't match the actual envs/load path entries.

### PR DESCRIPTION
**Pull request by barucden**
Filtering of `expanded_envs` caused that `envs[i]` and `editable_envs[i]` did not correspond to the same environment.

Before:
```
julia> insert!(LOAD_PATH, 2, mktempdir())
4-element Vector{String}:
 "@"
 "/tmp/jl_DRt9jd"
 "@v#.#"
 "@stdlib"

julia> using PyPlot
 │ Package PyPlot not found, but a package named PyPlot is available from a registry. 
 │ Install package?
 │   (@v1.9) pkg> add PyPlot 
 └ Select environment:
 > 1: `/tmp/jl_DRt9jd` (@)
   2: `~/.julia/environments/v1.9/Project.toml` (/tmp/jl_DRt9jd)
```

With the PR:
```
julia> insert!(LOAD_PATH, 2, mktempdir())
4-element Vector{String}:
 "@"
 "/tmp/jl_x6zoyq"
 "@v#.#"
 "@stdlib"

julia> using PyPlot
 │ Package PyPlot not found, but a package named PyPlot is available from a registry. 
 │ Install package?
 │   (@v1.9) pkg> add PyPlot 
 └ Select environment:
 > 1: `/tmp/jl_x6zoyq` (/tmp/jl_x6zoyq)
   2: `~/.julia/environments/v1.9/Project.toml` (@v#.#)
```

Fixes #3031.

~~Regarding the implementation -- does `Base.load_path_expand` ever return `nothing` if given a non-`nothing` input? If not, then the code get get simpler. (I just followed the previous implementation.)~~

Also another side question: has it been discussed what should happen if there are >9 editable_envs? In that case, `only("$(n)")` fails.

### CODE REVIEW

**Comment by barucden** [comment]
@IanButterworth I kindly ask you, the feature's author, for a review

File: src/REPLMode/REPLMode.jl [hunk 1]
```diff
@@ -717,13 +717,17 @@ function try_prompt_pkg_add(pkgs::Vector{Symbol})
...
     elseif lower_resp in ["o"]
         editable_envs = filter(v -> v != "@stdlib", LOAD_PATH)
-        expanded_envs = Base.load_path_expand.(editable_envs)
-        envs = convert(Vector{String}, filter(x -> !isnothing(x), expanded_envs))
         option_list = String[]
         keybindings = Char[]
-        for i in 1:length(envs)
-            push!(option_list, "$(i): $(pathrepr(envs[i])) ($(editable_envs[i]))")
-            push!(keybindings, only("$i"))
+        for i in 1:length(editable_envs)
```
Comment (IanButterworth) [inline src/REPLMode/REPLMode.jl:722]: I think it's reasonable to limit this to 9
```suggestion
        for i in 1:min(length(editable_envs), 9)
```

**Comment by barucden** [comment]
Done. Thanks for the review!
