### PR TITLE
Error if the stdlib version requested mismatches current version

### LINKED ISSUE #4334: Pkg.add should error when the wrong version of a fixed stdlib is added
```
julia> versioninfo()
Julia Version 1.13.0-DEV.897

(jl_rlcbl6) pkg> add Pkg@1.12
    Updating `/private/var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_rlcbl6/Project.toml`
  [44cfe95a] + Pkg v1.13.0
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes #4334 

```
(jl_TIjQ4O) pkg> add Pkg@1.14
ERROR: Cannot add stdlib `Pkg` with version specification `1.14`.
The current Julia version 1.13.0-DEV.897 uses `Pkg` v1.13.0.

(jl_TIjQ4O) pkg> add Pkg@1.12
ERROR: Cannot add stdlib `Pkg` with version specification `1.12`.
The current Julia version 1.13.0-DEV.897 uses `Pkg` v1.13.0.
```

I think this is also the only time we actually test that upgradable stdlibs are upgradable (downgradable)?

### CODE REVIEW

File: src/Operations.jl [hunk 1]
```diff
@@ -1663,7 +1697,9 @@ function rm(ctx::Context, pkgs::Vector{PackageSpec}; mode::PackageMode)
     return show_update(ctx.env, ctx.registries; io = ctx.io)
 end
 
-update_package_add(ctx::Context, pkg::PackageSpec, ::Nothing, is_dep::Bool) = pkg
+function update_package_add(ctx::Context, pkg::PackageSpec, ::Nothing, is_dep::Bool)
+    return pkg
```
Comment (KristofferC) [inline src/Operations.jl]: intended?

**Review by KristofferC — APPROVED** [review]
LGTM
