### PR TITLE
Precomp: Halve the default number of precompilation tasks in windows to avoid ReadOnlyMemoryError

### LINKED ISSUE #2323: Precompilation failure on Windows with julia 1.6 beta1
I am getting errors where packages fail to precompile in parallel, either with a crash or just never terminate, even though things work when precompiling normally.

Here is the environment, though I have seen this happen consistently with various sets of packages:

```
[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
```

```
(@v1.6) pkg> up
    Updating registry at `C:\Users\Jeremy\.julia\registries\General`
   Installed JLLWrappers ─ v1.2.0
No Changes to `C:\Users\Jeremy\.julia\environments\v1.6\Project.toml`
Updating `C:\Users\Jeremy\.julia\environments\v1.6\Manifest.toml`
  [692b3bcd] ↑ JLLWrappers v1.1.4 ⇒ v1.2.0
Precompiling project...
  Progress [======>                                  ]  3/23
  ◐ URIs
  ◒ Parsers
  ✓ JLLWrappers
  ✗ DataAPI
  ◐ IniFile
  ◐ MsgPack
  ◐ IteratorInterfaceExtensions
  ◒ ProgressMeter
  ✗ MbedTLS_jll
  ◓ FuzzyCompletions
  ◒ DataValueInterfaces
  ◓ Zlib_jll
  ◐ MbedTLS
  ◒ LibSSH2_jll
Internal error: encountered unexpected error in runtime:
ReadOnlyMemoryError()
reset_page at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1127 [inlined]
add_page at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1159
jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1212
UseRef at .\compiler/ssair\ir.jl:307 [inlined]
UseRefIterator at .\compiler/ssair\ir.jl:312 [inlined]
userefs at .\compiler/ssair\ir.jl:427 [inlined]
count_added_node! at .\compiler/ssair\ir.jl:646
setindex! at .\compiler/ssair\ir.jl:758
setindex! at .\compiler/ssair\ir.jl:766 [inlined]
ir_inline_item! at .\compiler/ssair\inlining.jl:337
batch_inline! at .\compiler/ssair\inlining.jl:549
ssa_inlining_pass! at .\compiler/ssair\inlining.jl:71
jfptr_ssa_inlining_passNOT._9828.clone_1 at C:\Users\Jeremy\AppData\Local\Julia-1.6.0-beta1\lib\julia\sys.dll (unknown line)
run_passes at .\compiler/ssair\driver.jl:128
optimize at .\compiler\optimize.jl:277 [inlined]
_typeinf at .\compiler\typeinfer.jl:239
typeinf at .\compiler\typeinfer.jl:211
abstract_call_method_with_const_args at .\compiler\abstractinterpretation.jl:319
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:166
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
abstract_call_method_with_const_args at .\compiler\abstractinterpretation.jl:319
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:166
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_apply at .\compiler\abstractinterpretation.jl:727
abstract_call_known at .\compiler\abstractinterpretation.jl:934
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call at .\compiler\abstractinterpretation.jl:1036
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1383
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_apply at .\compiler\abstractinterpretation.jl:727
abstract_call_known at .\compiler\abstractinterpretation.jl:934
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_apply at .\compiler\abstractinterpretation.jl:727
abstract_call_known at .\compiler\abstractinterpretation.jl:934
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_edge at .\compiler\typeinfer.jl:745
abstract_call_method at .\compiler\abstractinterpretation.jl:478
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:141
abstract_call_known at .\compiler\abstractinterpretation.jl:1015
abstract_call at .\compiler\abstractinterpretation.jl:1038
abstract_call at .\compiler\abstractinterpretation.jl:1022
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1144
typeinf_local at .\compiler\abstractinterpretation.jl:1398
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1454
_typeinf at .\compiler\typeinfer.jl:216
typeinf at .\compiler\typeinfer.jl:211
typeinf_ext at .\compiler\typeinfer.jl:835
typeinf_ext_toplevel at .\compiler\typeinfer.jl:868
typeinf_ext_toplevel at .\compiler\typeinfer.jl:864
jfptr_typeinf_ext_toplevel_13768.clone_1 at C:\Users\Jeremy\AppData\Local\Julia-1.6.0-beta1\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2224 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2406 [inlined]
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
jl_type_infer at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:296
jl_generate_fptr at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:340
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1957
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1911 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2216 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2406
_spawn_primitive at .\process.jl:99
#636 at .\process.jl:112 [inlined]
setup_stdios at .\process.jl:196
_spawn at .\process.jl:111 [inlined]
_spawn at .\process.jl:139
_spawn at .\process.jl:139
#open#645 at .\process.jl:374
open##kw at .\process.jl:361 [inlined]
open at .\process.jl:343
unknown function (ip: 0000000054a839c8)
create_expr_cache at .\loading.jl:1244
compilecache at .\loading.jl:1322
#212 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:1125
unknown function (ip: 0000000054aa7283)
with_logstate at .\logging.jl:491
with_logger at .\logging.jl:603 [inlined]
macro expansion at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:1124 [inlined]
#209 at .\task.jl:406
unknown function (ip: 0000000054aa46d3)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:839
┌ Error: Pkg.precompile error
│   exception =
│    IOError: could not spawn `'C:\Users\Jeremy\AppData\Local\Julia-1.6.0-beta1\bin\julia.exe' -Cnative '-JC:\Users\Jeremy\AppData\Local\Julia-1.6.0-beta1\lib\julia\sys.dll' -g1 -O0 --output-ji 'C:\Users\Jeremy\.julia\compiled\v1.6\fzf_jll\jl_5179.tmp' --output-incremental=yes --startup-file=no --history-file=no --warn-overwrite=yes --color=yes --eval 'eval(Meta.parse(read(stdin,String)))'`: unknown error (UNKNOWN)
│    Stacktrace:
│      [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
│        @ Base .\process.jl:99
│      [2] #636
│      [3] setup_stdios(f::Base.var"#636#637"{Cmd}, stdios::Vector{Any})
│        @ Base .\process.jl:196
│      [4] _spawn
│        @ .\process.jl:111 [inlined]
│      [5] _spawn(::Base.CmdRedirect, ::Vector{Any})
│        @ Base .\process.jl:139
│      [6] open(cmds::Base.CmdRedirect, stdio::Base.TTY; write::Bool, read::Bool)
│        @ Base .\process.jl:374
│      [7] open(cmds::Base.CmdRedirect, mode::String, stdio::Base.TTY)
│        @ Base .\process.jl:343
│      [8] create_expr_cache(pkg::Base.PkgId, input::String, output::String, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, internal_stderr::IOBuffer, internal_stdout::Base.DevNull)
│        @ Base .\loading.jl:1244
│      [9] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IOBuffer, internal_stdout::Base.DevNull)
  Progress [=======>                                 ]  4/23
  ◓ URIs
  ◐ Parsers
  ✗ DataAPI
  ◓ IniFile
  ◓ MsgPack
  ◓ IteratorInterfaceExtensions
  ◐ ProgressMeter
  ✗ MbedTLS_jll
  ◑ FuzzyCompletions
  ◐ DataValueInterfaces
  ✗ Zlib_jll
  ◓ MbedTLS
  ◐ LibSSH2_jll
  ◑ fzf_jll
Jeremy@NEWTON  ~                                                                                                             [17:03]
❯ julia16
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-beta1.0 (2021-01-08)
 _/ |\__'_|_|_|\__'_|  |  release-1.6/b84990e1ac (fork: 107 commits, 30 days)
|__/                   |

(@v1.6) pkg> up
    Updating registry at `C:\Users\Jeremy\.julia\registries\General`
No Changes to `C:\Users\Jeremy\.julia\environments\v1.6\Project.toml`
No Changes to `C:\Users\Jeremy\.julia\environments\v1.6\Manifest.toml`
Precompiling project...
  Progress [======================================>  ]  18/19
  ✗ Parsers
  ✗ DataAPI
  ✗ IniFile
  ✗ MsgPack
  ✗ IteratorInterfaceExtensions
  ✗ ProgressMeter
  ✗ MbedTLS_jll
  ✗ FuzzyCompletions
  ✗ DataValueInterfaces
  ✗ Zlib_jll
  ✗ MbedTLS
  ✗ LibSSH2_jll
  ✗ TableTraits
  ✗ JSON
  ◐ BenchmarkTools
 Interrupted: Exiting precompilation...

julia> using BenchmarkTools
[ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]

julia> using ProgressMeter
[ Info: Precompiling ProgressMeter [92933f4c-e287-5a05-a399-4b506db050ca]
```

### PR DESCRIPTION
**Pull request by ianshmean**
Hopefully a temporary fix for #2323 

This will mean precomp will be slower on windows, but still a lot faster than <v1.6

Fixes #2323

### CODE REVIEW

**Comment by ianshmean** [comment]
Users can still investigate increasing the number of tasks back to normal with
```
ENV["JULIA_NUM_PRECOMPILE_TASKS"] = Sys.CPU_THREADS + 1
```

File: src/API.jl [hunk 1]
```diff
@@ -984,7 +984,12 @@ function precompile(ctx::Context; internal_call::Bool=false, kwargs...)
     Context!(ctx; kwargs...)
     instantiate(ctx; allow_autoprecomp=false, kwargs...)
     time_start = time_ns()
-    num_tasks = parse(Int, get(ENV, "JULIA_NUM_PRECOMPILE_TASKS", string(Sys.CPU_THREADS::Int + 1)))
+
+    # Windows sometimes hits a ReadOnlyMemoryError, so we halve the default number of tasks. Issue #2323
+    # TODO: Investigate why this happens in windows and restore the full task limit
+    default_num_tasks = Sys.iswindows() ? round(Int, Sys.CPU_THREADS::Int / 2) + 1 : Sys.CPU_THREADS::Int + 1
```
Comment (fredrikekre) [inline src/API.jl:990]:
```suggestion
    default_num_tasks = Sys.iswindows() ? div(Sys.CPU_THREADS::Int, 2) + 1 : Sys.CPU_THREADS::Int + 1
```

**Review by fredrikekre — APPROVED** [review]
I guess the underlying problem isn't to blame on Pkg and should be fixed upstream?

**Comment by ianshmean** [comment]
> I guess the underlying problem isn't to blame on Pkg and should be fixed upstream?

Indeed. Perhaps we can leave https://github.com/JuliaLang/julia/issues/39396 on base as a tracking issue
