### PR TITLE
Fix `preview` and update completions

### LINKED ISSUE #600: Preview command parsing failures
It seems like the parsing involved with `preview` is broken on the latest `master`:

```julia
julia> Pkg.add("Example"; preview = true)
───── Preview mode ─────
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [7876af07] + Example v0.5.1
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [7876af07] + Example v0.5.1
  Building skipping building in preview mode
───── Preview mode ─────

(v1.0) pkg> preview add Example
ERROR: Wrong number of arguments

(v1.0) pkg> preview up
ERROR: MethodError: Cannot `convert` an object of type String to an object of type Pkg.REPLMode.CommandSpec
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:154
  Pkg.REPLMode.CommandSpec(::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:111
Stacktrace:
 [1] Pkg.REPLMode.PkgCommand(::Array{Any,1}, ::String, ::Array{Any,1}, ::Array{Pkg.Types.PackageSpec,1}) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:325
 [2] do_cmd!(::Pkg.REPLMode.PkgCommand, ::REPL.LineEditREPL) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:535
 [3] #do_cmd#30(::Bool, ::Function, ::REPL.LineEditREPL, ::String) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:507
 [4] do_cmd at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:503 [inlined]
 [5] (::getfield(Pkg.REPLMode, Symbol("##41#44")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/Pkg/src/REPLMode.jl:842
 [6] #invokelatest#1 at ./essentials.jl:686 [inlined]
 [7] invokelatest at ./essentials.jl:685 [inlined]
 [8] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/REPL/src/LineEdit.jl:2261
 [9] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:1029
 [10] run_repl(::REPL.AbstractREPL, ::Any) at /home/user/julia-dev/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:191
 [11] (::getfield(Base, Symbol("##720#722")){Bool,Bool,Bool,Bool})(::Module) at ./logging.jl:311
 [12] #invokelatest#1 at ./essentials.jl:686 [inlined]
 [13] invokelatest at ./essentials.jl:685 [inlined]
 [14] macro expansion at ./logging.jl:308 [inlined]
 [15] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:330
 [16] exec_options(::Base.JLOptions) at ./client.jl:242
 [17] _start() at ./client.jl:421
```

### PR DESCRIPTION
**Pull request by 00vareladavid**
Should resolve #600

### CODE REVIEW

File: src/resolve/FieldValues.jl [hunk 1]
```diff
@@ -74,7 +74,7 @@ validmax(a::FieldValue) = a.l0 >= 0
 
 # like usual indmax, but favors the highest indices
 # in case of a tie
-function Base.indmax(f::Field)
+function indmax(f::Field)
```
Comment (fredrikekre) [inline src/resolve/FieldValues.jl]: `Base.argmax`?

File: test/repl.jl [hunk 2]
```diff
@@ -870,6 +870,17 @@ end
     end end end
 end
 
+@testset "preview" begin
+    temp_pkg_dir() do project_path; cd_tempdir() do tmpdir; with_temp_env() do;
+        pkg"add Example"
+        pkg"preview 'rm Example'"
```
Comment (fredrikekre) [inline test/repl.jl]: Why the `'`s?

File: src/resolve/FieldValues.jl (hunk 1 above)
Comment (00vareladavid) [reply src/resolve/FieldValues.jl]: Yeah, I just saw that it is supposed to be `Base.argmax` from your PR

Comment (fredrikekre) [reply src/resolve/FieldValues.jl]: On second thought, we might as well just not extend the Base function, no reason to.

File: test/repl.jl (hunk 2 above)
Comment (00vareladavid) [reply test/repl.jl]: The main reason is that it avoids any special parsing for `preview`. But now that I think about, an equally noninvasive fix would be to replace `preview` with a `--preview` meta option.

Comment (fredrikekre) [reply test/repl.jl]: So `pkg> preview add Example` doesn't work anymore? You need `pkg> preview 'add Example'`?

Comment (00vareladavid) [reply test/repl.jl]: If we really want `pkg> preview add Example` syntax though I'll bite the bullet and get it done.

Comment (00vareladavid) [reply test/repl.jl]: I've opted to go with both, in case the meta option syntax is a breaking change. The code would be cleaner with `preview` as just a meta option, but perhaps its too late for that?

**Comment by 00vareladavid** [comment]
Ok, things seem to be working. I'll see if I can get it a bit faster though.

**Comment by 00vareladavid** [comment]
Caching only slightly improved performance, but it is decently fast on subsequent calls to `REPLMode.completions`. What is bugging me is the time it takes for the first call. I think I'm not helping the type system enough? I'm pretty sure I'm not doing any unnecessary work. I tried a bunch of different things (using enums, different refactorings, throwing it under the profiler, etc) but I've had no luck.

@fredrikekre @KristofferC, if either of you have the time, any advice on what else I could try would be very appreciated. Maybe I'm missing something obvious?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/28608 should fix compilation time so we dont have to worry about a list of precompilation statements here anymore.

**Comment by KristofferC** [comment]
Bump, would be nice to get this in and close a bug labeled issue.

**Comment by 00vareladavid** [comment]
K, I'll get it done today

**Comment by KristofferC** [comment]
To run the tests you write `bors try` (without the code quotes)

**Comment by 00vareladavid** [comment]
So would it be possible to drop `pkg> preview add Example` in favor of `pkg> --preview add Example`? Or too late for that? I ask because it would avoid some special casing for `preview`.

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

File: test/repl.jl [hunk 3]
```diff
@@ -386,7 +420,7 @@ temp_pkg_dir() do project_path; cd(project_path) do
         pkg"add Example"
         c, r = test_complete("rm Exam")
         @test "Example" in c
-        c, r = test_complete("add --man")
+        c, r = test_complete("up --man")
```
Comment (KristofferC) [inline test/repl.jl]: Why was this test changed?

File: test/repl.jl [hunk 4]
```diff
@@ -397,7 +431,6 @@ temp_pkg_dir() do project_path; cd(project_path) do
         @test "remove" in c
         c, r = test_complete("help r")
         @test "remove" in c
-        @test !("rm" in c)
```
Comment (KristofferC) [inline test/repl.jl]: Why remove this test?

File: test/repl.jl (hunk 3 above)
Comment (00vareladavid) [reply test/repl.jl]: Completions depend on the command. `add` does not have a `--manifest` option, so it will not complete. `up` does have a `--manifest` option

File: test/repl.jl (hunk 4 above)
Comment (00vareladavid) [reply test/repl.jl]: Because `rm` is a valid command. Not sure why this was not allowed before?

Comment (KristofferC) [reply test/repl.jl]: Because we didn't want to show both the short and long form of the same command in the completion.

File: test/repl.jl (hunk 3 above)
Comment (KristofferC) [reply test/repl.jl]: Cool!

File: test/repl.jl (hunk 4 above)
Comment (00vareladavid) [reply test/repl.jl]: K, I can bring that behavior back if needed. Note that `command_declarations` currently does not differentiate between long and short forms. It just accepts a list of names which refer to the same command. Perhaps that is too flexible?

Comment (KristofferC) [reply test/repl.jl]: I think it is enough with one canonical (long) form and an optional short form.

Comment (00vareladavid) [reply test/repl.jl]: Sounds good. I'll change it

File: test/repl.jl (hunk 3 above)
Comment (00vareladavid) [reply test/repl.jl]: Glad you think so :grin:

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

**Comment by KristofferC** [comment]
Sigh, this wasn't squashed either.

**Comment by KristofferC** [comment]
Please try to keep your branches a bit more tidy (a few commits, no merge commits on them etc).

**Comment by 00vareladavid** [comment]
Sure, I'll keep that in mind in the future @KristofferC
