### PR TITLE
Make files read only more often

### LINKED ISSUE #729: inconsistent permissions for packages (1.0.0)
While most packages gets installed with `755` permission inside `<depot>/packages/` there are a few packages that gets installed with restrictive `700` permission.

```bash
# find . -type d -perm 700 
./packages/MLBase/85ImQ
./packages/TensorFlow/Aw19b
./packages/Feather/3q0Pp
./packages/JLD2/KjBIK
./packages/PlotlyJS/7k06k
./packages/NaiveBayes/3zI5c
./packages/DecisionTree/RN3J3
./packages/Luxor/M8Q12
```
below is the status of installed packages, it seems all the packages with restrictive permission are on `rev=master`. But not all the packages with `rev=master` have restrictive permission.

```
(v1.0) pkg> st
    Status `/opt/juliadepot/environments/v1.0/Project.toml`
  [67c07d97] Automa v0.7.0
  [336ed68f] CSV v0.3.1
  [5d742f6a] CSVFiles v0.9.1
  [159f3aea] Cairo v0.5.6
  [aaaa29a8] Clustering v0.12.0
  [944b1d66] CodecZlib v0.5.0
  [35d6a980] ColorSchemes v2.0.0
  [3da002f7] ColorTypes v0.7.4
  [5ae59095] Colors v0.9.4
  [34da2185] Compat v1.1.0
  [150eb455] CoordinateTransformations v0.5.0
  [a8cc5b0e] Crayons v1.0.0
  [717857b8] DSP v0.5.1
  [124859b0] DataDeps v0.5.2
  [a93c6f00] DataFrames v0.13.1
  [1313f7d8] DataFramesMeta v0.4.0
  [864edb3b] DataStructures v0.11.1
  [5721bf48] DataVoyager v0.3.0
  [7806a523] DecisionTree v0.8.1+ #master (https://github.com/bensadeghi/DecisionTree.jl.git)
  [31c24e10] Distributions v0.16.4
  [c04bee98] ExcelReaders v0.10.2
  [becb17da] Feather v0.4.0+ #master (https://github.com/JuliaData/Feather.jl.git)
  [b675d258] FeatherFiles v0.5.1
  [5789e2e9] FileIO v1.0.1
  [587475ba] Flux v0.6.7
  [59287772] Formatting v0.3.3
  [f6369f11] ForwardDiff v0.9.0
  [38e38edf] GLM v1.0.0
  [28b8d3ca] GR v0.34.1
  [92fee26a] GZip v0.5.0
  [f67ccb44] HDF5 v0.10.2
  [7073ff75] IJulia v1.11.1
  [6a3955dd] ImageFiltering v0.4.1
  [6218d12a] ImageMagick v0.7.1
  [02fcd773] ImageTransformations v0.5.2
  [916415d5] Images v0.16.0
  [c601a237] Interact v0.9.0
  [c8e1da08] IterTools v1.0.0
  [1c8ee90f] IterableTables v0.8.3
  [033835bb] JLD2 v0.1.2+ #master (https://github.com/simonster/JLD2.jl.git)
  [682c06a0] JSON v0.19.0
  [7f8f8fb0] LearnBase v0.2.2
  [4e8a8231] LearningStrategies v0.4.0
  [30fc2ffe] LossFunctions v0.4.0
  [ae8d54c2] Luxor v0.12.0+ #master (https://github.com/JuliaGraphics/Luxor.jl.git)
  [f0e99cf1] MLBase v0.8.0+ #master (https://github.com/JuliaStats/MLBase.jl.git)
  [9920b226] MLDataPattern v0.5.0
  [cc2ba9b6] MLDataUtils v0.4.0
  [66a33bbf] MLLabelUtils v0.4.1
  [d4533929] MNIST v0.0.2
  [9bbee03b] NaiveBayes v0.3.1+ #master (https://github.com/dfdx/NaiveBayes.jl.git)
  [b8a86587] NearestNeighbors v0.4.1
  [6c575b1c] NumericIO v0.3.0
  [a15396b6] OnlineStats v0.19.1
  [8314cec4] PGFPlotsX v0.3.2
  [eadc2687] Pandas v1.0.1
  [f0f68f2c] PlotlyJS v0.11.0+ #master (https://github.com/sglyon/PlotlyJS.jl.git)
  [92933f4c] ProgressMeter v0.6.0
  [438e738f] PyCall v1.18.4
  [d330b81b] PyPlot v2.6.3
  [1a8c2f83] Query v0.10.0
  [d71aba96] ReadStat v0.4.1
  [189a3867] Reexport v0.2.0
  [c4c386cf] Rsvg v0.2.2+ #master (https://github.com/lobingera/Rsvg.jl.git)
  [992d4aef] Showoff v0.2.1
  [1463e38c] StatFiles v0.6.1
  [2913bbd2] StatsBase v0.25.0
  [382cd787] TableTraitsUtils v0.3.1
  [1d978283] TensorFlow v0.10.0+ #master (https://github.com/malmaud/TensorFlow.jl.git)
  [b8865327] UnicodePlots v0.3.1
  [98cad3c8] ValueHistories v0.5.0
  [0ae4a718] VegaDatasets v0.4.1
  [112f6efa] VegaLite v0.4.0
  [44d3d7a6] Weave v0.6.1
  [ddb6d928] YAML v0.3.2+ #master (https://github.com/BioJulia/YAML.jl.git)
  [e88e6eb3] Zygote v0.1.0
```

### LINKED ISSUE #1313: chmod bug
to replicate:
1. remove or  mv ~/.julia to start from zero packages
2. run julia and update to initialize .julia
3. ]add TSML breaks with *chmod error* but ]add TSML#v2.3.7 works
Note: both points to the latest version which should be exactly the same.
4. also, ]add TSML again works after the chmod error

Note: I used Reexport recently. Is it possible it has something to do with the macro?

errors:
-----------
ERROR: Error when installing package TSML:
IOError: chmod: no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error at ./libuv.jl:85 [inlined]
 [2] #chmod#16(::Bool, ::Function, ::String, ::UInt64) at ./file.jl:834
 [3] chmod at ./file.jl:833 [inlined]
 [4] set_readonly(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:70
 [5] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:598 [inlined]
 [6] (::getfield(Pkg.Operations, Symbol("##26#29")){Symbol,Pkg.Types.Context,Dict{Base.UUID,Base.SHA1},Dict{Base.UUID,Array{String,1}}})() at ./task.jl:259

### LINKED ISSUE #1382: add(PackageSpec with rev) results in strict permissions
Reproducible on Julia 1.2 (`docker run -it --rm julia /bin/bash`):

```
# JULIA_DEPOT_PATH=/usr/local/share/julia \
  julia -e 'using Pkg; Pkg.add([PackageSpec(name="CUDAapi", rev="v1.1.0")])'
 Resolving package versions...
  Updating `/usr/local/share/julia/environments/v1.2/Project.toml`
  [3895d2a7]   CUDAapi v1.1.0 #v1.1.0 (https://github.com/JuliaGPU/CUDAapi.jl.git)
  Updating `/usr/local/share/julia/environments/v1.2/Manifest.toml`
  [3895d2a7]   CUDAapi v1.1.0 #v1.1.0 (https://github.com/JuliaGPU/CUDAapi.jl.git)

# find /usr/local/share/julia/packages/ -maxdepth 2 -mindepth 2 -exec ls -ld {} \;
drwx------ 4 root root 4096 Sep 13 11:03 /usr/local/share/julia/packages/CUDAapi/lP4MU
```

Whereas dropping the `rev` results in more accessible file permissions:

```
# JULIA_DEPOT_PATH=/usr/local/share/julia \
  julia -e 'using Pkg; Pkg.add([PackageSpec(name="CUDAapi")])'
 Resolving package versions...
 Installed CUDAapi ─ v1.1.0
  Updating `/usr/local/share/julia/environments/v1.2/Project.toml`
  [3895d2a7] + CUDAapi v1.1.0
  Updating `/usr/local/share/julia/environments/v1.2/Manifest.toml`
  [3895d2a7] + CUDAapi v1.1.0
  [8f399da3] + Libdl 
  [56ddb016] + Logging 

# find /usr/local/share/julia/packages/ -maxdepth 2 -mindepth 2 -exec ls -ld {} \;
drwxrwxr-x 4 root root 4096 Sep 13 11:03 /usr/local/share/julia/packages/CUDAapi/lP4MU
```

Not sure if this is intended, but I ran into this while creating a Dockerfile that embeds known-good package versions.

### PR DESCRIPTION
**Pull request by fredrikekre**
Make files read only when installing a given git revision, and when installing a package because of a dependency from a Pkg.develop'd package, fixes #729, fixes #1313, fixes #1382.

### CODE REVIEW

File: src/Operations.jl [hunk 1]
```diff
@@ -1045,7 +1045,7 @@ function develop(ctx::Context, pkgs::Vector{PackageSpec}, new_git::Vector{UUID};
     # resolve & apply package versions
     resolve_versions!(ctx, pkgs)
     update_manifest!(ctx, pkgs)
-    new_apply = download_source(ctx, pkgs; readonly=false)
+    new_apply = download_source(ctx, pkgs; readonly=true)
```
Comment (fredrikekre) [inline src/Operations.jl]: Even though this is in `develop` we should install the dependencies as read-only.

File: src/Types.jl [hunk 2]
```diff
@@ -725,6 +725,7 @@ function instantiate_pkg_repo!(ctx::Context, pkg::PackageSpec, cached_repo::Unio
     isdir(version_path) && return false
     mkpath(version_path)
     mv(cached_repo, version_path; force=true)
+    set_readonly(version_path)
```
Comment (fredrikekre) [inline src/Types.jl]: This change deals with installing from a git revision.
